// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package ecs

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
	fwvalidators "github.com/volcengine/terraform-provider-volcenginecc/internal/validators"
)

func init() {
	registry.AddResourceFactory("volcenginecc_ecs_launch_template_version", launchtemplateVersionResource)
}

// launchtemplateVersionResource returns the Terraform volcenginecc_ecs_launch_template_version resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::ECS::LaunchtemplateVersion resource.
func launchtemplateVersionResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: DeploymentSetGroupNumber
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "当ECS实例要加入或调整的部署集策略为部署集组高可用策略（AvailabilityGroup）时，可以通过该参数指定实例在部署集中的分组号。",
		//	  "type": "integer"
		//	}
		"deployment_set_group_number": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "当ECS实例要加入或调整的部署集策略为部署集组高可用策略（AvailabilityGroup）时，可以通过该参数指定实例在部署集中的分组号。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
				int64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DeploymentSetId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例需要加入的部署集ID。",
		//	  "type": "string"
		//	}
		"deployment_set_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例需要加入的部署集ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的描述。",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例的描述。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Eip
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例绑定的公网IP信息。",
		//	  "properties": {
		//	    "Bandwidth": {
		//	      "description": "公网IP的带宽上限，单位：Mbps。取值范围：1～200。默认值：1。",
		//	      "maximum": 200,
		//	      "type": "integer"
		//	    },
		//	    "BandwidthPackageId": {
		//	      "description": "共享带宽包的ID，表示将公网IP加入到共享带宽包。",
		//	      "type": "string"
		//	    },
		//	    "BillingType": {
		//	      "description": "公网IP的计费方式，取值：2：按量计费-按带宽上限计费。3：按量计费-按实际流量计费。",
		//	      "type": "integer"
		//	    },
		//	    "ISP": {
		//	      "description": "公网IP的线路类型，取值：BGP：BGP（多线）。ChinaMobile：中国移动静态单线。ChinaTelecom：国电信静态单线。ChinaUnicom：中国联通静态单线。",
		//	      "type": "string"
		//	    },
		//	    "ReleaseWithInstance": {
		//	      "description": "公网IP是否随实例删除，仅按量计费公网IP生效。",
		//	      "type": "boolean"
		//	    },
		//	    "SecurityProtectionInstanceId": {
		//	      "description": "安全防护包ID。",
		//	      "type": "integer"
		//	    },
		//	    "SecurityProtectionTypes": {
		//	      "description": "公网IP的安全防护类型。取值：AntiDDoS_Enhanced：申请增强防护类型的公网IP，可加入到DDoS原生防护（企业版）实例。",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"eip": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Bandwidth
				"bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "公网IP的带宽上限，单位：Mbps。取值范围：1～200。默认值：1。",
					Optional:    true,
					Computed:    true,
					Validators: []validator.Int64{ /*START VALIDATORS*/
						int64validator.AtMost(200),
					}, /*END VALIDATORS*/
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: BandwidthPackageId
				"bandwidth_package_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "共享带宽包的ID，表示将公网IP加入到共享带宽包。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: BillingType
				"billing_type": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "公网IP的计费方式，取值：2：按量计费-按带宽上限计费。3：按量计费-按实际流量计费。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: ISP
				"isp": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "公网IP的线路类型，取值：BGP：BGP（多线）。ChinaMobile：中国移动静态单线。ChinaTelecom：国电信静态单线。ChinaUnicom：中国联通静态单线。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: ReleaseWithInstance
				"release_with_instance": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "公网IP是否随实例删除，仅按量计费公网IP生效。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
						boolplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: SecurityProtectionInstanceId
				"security_protection_instance_id": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "安全防护包ID。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: SecurityProtectionTypes
				"security_protection_types": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "公网IP的安全防护类型。取值：AntiDDoS_Enhanced：申请增强防护类型的公网IP，可加入到DDoS原生防护（企业版）实例。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
						setplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "实例绑定的公网IP信息。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
				objectplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: HostName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的主机名。Linux系统的主机名长度限制为2～59个字符。Windows系统的主机名长度限制为2～10个字符。",
		//	  "type": "string"
		//	}
		"host_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例的主机名。Linux系统的主机名长度限制为2～59个字符。Windows系统的主机名长度限制为2～10个字符。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: HpcClusterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "当创建高性能计算GPU型实例时，请指定高性能计算集群ID。",
		//	  "type": "string"
		//	}
		"hpc_cluster_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "当创建高性能计算GPU型实例时，请指定高性能计算集群ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ImageId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "镜像ID。",
		//	  "type": "string"
		//	}
		"image_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "镜像ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ImageName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "镜像名称。",
		//	  "type": "string"
		//	}
		"image_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "镜像名称。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// ImageName is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: InstanceChargeType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "default": "PostPaid",
		//	  "description": "实例和云盘的计费类型，取值：PostPaid：按量计费。PrePaid：包年包月。Esi：弹性预约实例。Segmented：时段型弹性预约实例。",
		//	  "type": "string"
		//	}
		"instance_charge_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例和云盘的计费类型，取值：PostPaid：按量计费。PrePaid：包年包月。Esi：弹性预约实例。Segmented：时段型弹性预约实例。",
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString("PostPaid"),
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: InstanceName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的名称。",
		//	  "maxLength": 128,
		//	  "type": "string"
		//	}
		"instance_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例的名称。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(128),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: InstanceTypeId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的规格。",
		//	  "type": "string"
		//	}
		"instance_type_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例的规格。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: KeepImageCredential
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "是否保留镜像设置，取值：true：保留镜像设置，保留后将使用镜像预设的密码或密钥对登录实例。false（默认）：不保留镜像设置。",
		//	  "type": "boolean"
		//	}
		"keep_image_credential": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "是否保留镜像设置，取值：true：保留镜像设置，保留后将使用镜像预设的密码或密钥对登录实例。false（默认）：不保留镜像设置。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
				boolplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: KeyPairName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例绑定的密钥对。",
		//	  "type": "string"
		//	}
		"key_pair_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例绑定的密钥对。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: LaunchTemplateId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例启动模板 ID。",
		//	  "type": "string"
		//	}
		"launch_template_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例启动模板 ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: NetworkInterfaces
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例挂载的网卡信息。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "SecurityGroupIds": {
		//	        "description": "网卡关联的安全组ID。",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "SubnetId": {
		//	        "description": "实例的私有网络子网ID。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"network_interfaces": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: SecurityGroupIds
					"security_group_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
						ElementType: types.StringType,
						Description: "网卡关联的安全组ID。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
							setplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: SubnetId
					"subnet_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "实例的私有网络子网ID。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "实例挂载的网卡信息。\n 特别提示: 在使用 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
				setplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例所属项目。",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例所属项目。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ScheduledInstance
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "弹性预约单信息。",
		//	  "properties": {
		//	    "ScheduledInstanceDescription": {
		//	      "description": "弹性预约单的描述。",
		//	      "type": "string"
		//	    },
		//	    "ScheduledInstanceName": {
		//	      "description": "弹性预约单的名称。",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"scheduled_instance": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: ScheduledInstanceDescription
				"scheduled_instance_description": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "弹性预约单的描述。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: ScheduledInstanceName
				"scheduled_instance_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "弹性预约单的名称。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "弹性预约单信息。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
				objectplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecurityEnhancementStrategy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "是否开启安全加固。Active:开启安全加固，仅对公共镜像生效。InActive:关闭安全加固，对所有镜像生效。",
		//	  "enum": [
		//	    "Active",
		//	    "InActive"
		//	  ],
		//	  "type": "string"
		//	}
		"security_enhancement_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "是否开启安全加固。Active:开启安全加固，仅对公共镜像生效。InActive:关闭安全加固，对所有镜像生效。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.OneOf(
					"Active",
					"InActive",
				),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SpotPriceLimit
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "抢占式实例的每小时最高价格。",
		//	  "type": "number"
		//	}
		"spot_price_limit": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "抢占式实例的每小时最高价格。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Float64{ /*START PLAN MODIFIERS*/
				float64planmodifier.UseStateForUnknown(),
				float64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SpotStrategy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "按量计费的抢占式策略。取值：NoSpot：表示创建正常按量计费实例。SpotAsPriceGo：系统自动出价，跟随当前市场实际价格的抢占式实例。SpotWithPriceLimit：设置出价上限的抢占式实例。",
		//	  "type": "string"
		//	}
		"spot_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "按量计费的抢占式策略。取值：NoSpot：表示创建正常按量计费实例。SpotAsPriceGo：系统自动出价，跟随当前市场实际价格的抢占式实例。SpotWithPriceLimit：设置出价上限的抢占式实例。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SuffixIndex
		// Cloud Control resource type schema:
		//
		//	{
		//	  "default": 1,
		//	  "description": "有序后缀的起始序号。",
		//	  "maximum": 999,
		//	  "minimum": 1,
		//	  "type": "integer"
		//	}
		"suffix_index": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "有序后缀的起始序号。",
			Optional:    true,
			Computed:    true,
			Default:     int64default.StaticInt64(1),
			Validators: []validator.Int64{ /*START VALIDATORS*/
				int64validator.Between(1, 999),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
				int64planmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的标签信息。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Key": {
		//	        "description": "给资源添加的用户标签的标签键。",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "给资源添加的用户标签的标签值。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "给资源添加的用户标签的标签键。",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							fwvalidators.NotNullString(),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "给资源添加的用户标签的标签值。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "实例的标签信息。\n 特别提示: 在使用 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
				setplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UniqueSuffix
		// Cloud Control resource type schema:
		//
		//	{
		//	  "default": false,
		//	  "description": "表示当创建多台实例时，是否为Hostname和InstanceName自动添加有序后缀。",
		//	  "type": "boolean"
		//	}
		"unique_suffix": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "表示当创建多台实例时，是否为Hostname和InstanceName自动添加有序后缀。",
			Optional:    true,
			Computed:    true,
			Default:     booldefault.StaticBool(false),
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
				boolplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UserData
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例的自定义数据。",
		//	  "type": "string"
		//	}
		"user_data": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例的自定义数据。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VersionDescription
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "模版版本描述。",
		//	  "type": "string"
		//	}
		"version_description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "模版版本描述。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VersionNumber
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "模板版本号。",
		//	  "type": "string"
		//	}
		"version_number": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "模板版本号。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Volumes
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例绑定的云盘信息。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "DeleteWithInstance": {
		//	        "description": "云盘是否随实例释放。",
		//	        "type": "boolean"
		//	      },
		//	      "ExtraPerformanceIOPS": {
		//	        "description": "云盘额外IOPS性能大小，仅ESSD FlexPL数据盘支持，单位为次/秒。 ExtraPerformanceTypeId为Balance或IOPS时需设置该参数。各个类型的额外性能取值范围如下：IOPS型：1～50000。Balance型：1～50000。",
		//	        "type": "integer"
		//	      },
		//	      "ExtraPerformanceThroughputMB": {
		//	        "description": "云盘额外吞吐性能大小，单位MB/s，仅ESSD FlexPL数据盘支持。 ExtraPerformanceTypeId为Throughput时需设置该参数。 取值范围：1～650。",
		//	        "type": "integer"
		//	      },
		//	      "ExtraPerformanceTypeId": {
		//	        "description": "云盘额外性能的类型，仅ESSD FlexPL数据盘支持。关于额外性能的更多介绍，请参见云盘额外性能。取值：Balance：均衡型额外性能。IOPS：IOPS型额外性能。Throughput：吞吐量型额外性能。",
		//	        "type": "string"
		//	      },
		//	      "Size": {
		//	        "description": "云盘大小，单位为GB。系统盘：ESSD_PL0：20~2048 PTSSD：10~500。数据盘：ESSD_PL0：10~32768 PTSSD：20~8192",
		//	        "type": "integer"
		//	      },
		//	      "SnapshotId": {
		//	        "description": "使用快照创建云盘，仅支持创建数据盘。您可以调用DescribeSnapshots接口查询快照ID。",
		//	        "type": "string"
		//	      },
		//	      "VolumeType": {
		//	        "description": "云盘类型。ESSD_PL0：极速型SSD PL0。PTSSD：性能型SSD。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"volumes": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: DeleteWithInstance
					"delete_with_instance": schema.BoolAttribute{ /*START ATTRIBUTE*/
						Description: "云盘是否随实例释放。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
							boolplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ExtraPerformanceIOPS
					"extra_performance_iops": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "云盘额外IOPS性能大小，仅ESSD FlexPL数据盘支持，单位为次/秒。 ExtraPerformanceTypeId为Balance或IOPS时需设置该参数。各个类型的额外性能取值范围如下：IOPS型：1～50000。Balance型：1～50000。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ExtraPerformanceThroughputMB
					"extra_performance_throughput_mb": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "云盘额外吞吐性能大小，单位MB/s，仅ESSD FlexPL数据盘支持。 ExtraPerformanceTypeId为Throughput时需设置该参数。 取值范围：1～650。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: ExtraPerformanceTypeId
					"extra_performance_type_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "云盘额外性能的类型，仅ESSD FlexPL数据盘支持。关于额外性能的更多介绍，请参见云盘额外性能。取值：Balance：均衡型额外性能。IOPS：IOPS型额外性能。Throughput：吞吐量型额外性能。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Size
					"size": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "云盘大小，单位为GB。系统盘：ESSD_PL0：20~2048 PTSSD：10~500。数据盘：ESSD_PL0：10~32768 PTSSD：20~8192",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: SnapshotId
					"snapshot_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "使用快照创建云盘，仅支持创建数据盘。您可以调用DescribeSnapshots接口查询快照ID。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: VolumeType
					"volume_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "云盘类型。ESSD_PL0：极速型SSD PL0。PTSSD：性能型SSD。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "实例绑定的云盘信息。\n 特别提示: 在使用 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
				setplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "私有网络ID。",
		//	  "type": "string"
		//	}
		"vpc_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "私有网络ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ZoneId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "实例所属可用区ID。",
		//	  "type": "string"
		//	}
		"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "实例所属可用区ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "实例启动模板版本是一系列实例配置信息的集合，用于快速购买实例。在模板中，您可以存储除密码外的全部配置信息，包括密钥对、计算规格、云盘、网络等，如果配置信息均有效，便可以一键成功购买实例，无需进行重复配置。",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::ECS::LaunchtemplateVersion").WithTerraformTypeName("volcenginecc_ecs_launch_template_version")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"bandwidth":                       "Bandwidth",
		"bandwidth_package_id":            "BandwidthPackageId",
		"billing_type":                    "BillingType",
		"delete_with_instance":            "DeleteWithInstance",
		"deployment_set_group_number":     "DeploymentSetGroupNumber",
		"deployment_set_id":               "DeploymentSetId",
		"description":                     "Description",
		"eip":                             "Eip",
		"extra_performance_iops":          "ExtraPerformanceIOPS",
		"extra_performance_throughput_mb": "ExtraPerformanceThroughputMB",
		"extra_performance_type_id":       "ExtraPerformanceTypeId",
		"host_name":                       "HostName",
		"hpc_cluster_id":                  "HpcClusterId",
		"image_id":                        "ImageId",
		"image_name":                      "ImageName",
		"instance_charge_type":            "InstanceChargeType",
		"instance_name":                   "InstanceName",
		"instance_type_id":                "InstanceTypeId",
		"isp":                             "ISP",
		"keep_image_credential":           "KeepImageCredential",
		"key":                             "Key",
		"key_pair_name":                   "KeyPairName",
		"launch_template_id":              "LaunchTemplateId",
		"network_interfaces":              "NetworkInterfaces",
		"project_name":                    "ProjectName",
		"release_with_instance":           "ReleaseWithInstance",
		"scheduled_instance":              "ScheduledInstance",
		"scheduled_instance_description":  "ScheduledInstanceDescription",
		"scheduled_instance_name":         "ScheduledInstanceName",
		"security_enhancement_strategy":   "SecurityEnhancementStrategy",
		"security_group_ids":              "SecurityGroupIds",
		"security_protection_instance_id": "SecurityProtectionInstanceId",
		"security_protection_types":       "SecurityProtectionTypes",
		"size":                            "Size",
		"snapshot_id":                     "SnapshotId",
		"spot_price_limit":                "SpotPriceLimit",
		"spot_strategy":                   "SpotStrategy",
		"subnet_id":                       "SubnetId",
		"suffix_index":                    "SuffixIndex",
		"tags":                            "Tags",
		"unique_suffix":                   "UniqueSuffix",
		"user_data":                       "UserData",
		"value":                           "Value",
		"version_description":             "VersionDescription",
		"version_number":                  "VersionNumber",
		"volume_type":                     "VolumeType",
		"volumes":                         "Volumes",
		"vpc_id":                          "VpcId",
		"zone_id":                         "ZoneId",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/ImageName",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/VersionNumber",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/VersionDescription",
		"/properties/LaunchTemplateId",
		"/properties/InstanceTypeId",
		"/properties/KeyPairName",
		"/properties/UserData",
		"/properties/InstanceName",
		"/properties/Description",
		"/properties/HostName",
		"/properties/ZoneId",
		"/properties/VpcId",
		"/properties/HpcClusterId",
		"/properties/InstanceChargeType",
		"/properties/SuffixIndex",
		"/properties/UniqueSuffix",
		"/properties/ProjectName",
		"/properties/SpotStrategy",
		"/properties/SpotPriceLimit",
		"/properties/ImageId",
		"/properties/ImageName",
		"/properties/SecurityEnhancementStrategy",
		"/properties/Volumes",
		"/properties/NetworkInterfaces",
		"/properties/Tags",
		"/properties/Eip",
		"/properties/ScheduledInstance",
		"/properties/DeploymentSetId",
		"/properties/DeploymentSetGroupNumber",
		"/properties/KeepImageCredential",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
