// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vke

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vke_default_node_pool", defaultNodePoolDataSource)
}

// defaultNodePoolDataSource returns the Terraform volcenginecc_vke_default_node_pool data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VKE::DefaultNodePool resource.
func defaultNodePoolDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AutoScaling
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool scaling policy configuration",
		//	  "properties": {
		//	    "DesiredReplicas": {
		//	      "description": "Configure the desired number of nodes in the node pool.",
		//	      "type": "integer"
		//	    },
		//	    "Enabled": {
		//	      "description": "Configure the switch for node pool auto scaling. Parameter values: false: disabled true: enabled",
		//	      "type": "boolean"
		//	    },
		//	    "MaxReplicas": {
		//	      "description": "Configure the maximum number of nodes in the node pool",
		//	      "type": "integer"
		//	    },
		//	    "MinReplicas": {
		//	      "description": "Configure the minimum number of nodes in the node pool",
		//	      "type": "integer"
		//	    },
		//	    "Priority": {
		//	      "description": "Priority",
		//	      "type": "integer"
		//	    },
		//	    "ScalingGroupId": {
		//	      "description": "Scaling group ID",
		//	      "type": "string"
		//	    },
		//	    "SubnetPolicy": {
		//	      "description": "Multi-subnet scheduling policy for the node pool. Parameter value description: ZoneBalance: availability zone balancing policy. Priority: subnet priority policy.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"auto_scaling": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: DesiredReplicas
				"desired_replicas": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Configure the desired number of nodes in the node pool.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Enabled
				"enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Configure the switch for node pool auto scaling. Parameter values: false: disabled true: enabled",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: MaxReplicas
				"max_replicas": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Configure the maximum number of nodes in the node pool",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: MinReplicas
				"min_replicas": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Configure the minimum number of nodes in the node pool",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Priority
				"priority": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Priority",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ScalingGroupId
				"scaling_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Scaling group ID",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SubnetPolicy
				"subnet_policy": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Multi-subnet scheduling policy for the node pool. Parameter value description: ZoneBalance: availability zone balancing policy. Priority: subnet priority policy.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Node pool scaling policy configuration",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ClusterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Cluster ID where the node pool is located",
		//	  "type": "string"
		//	}
		"cluster_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Cluster ID where the node pool is located",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool creation time",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Node pool creation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: KubernetesConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Kubernetes-related configuration for the node pool",
		//	  "properties": {
		//	    "AutoSyncDisabled": {
		//	      "description": "Whether to disable the automatic synchronization of label taints to existing nodes. Parameter value description: true: disabled, automatic synchronization is turned off. false: not disabled, automatic synchronization is turned on.",
		//	      "type": "boolean"
		//	    },
		//	    "Cordon": {
		//	      "description": "Node blocking configuration. Parameter value description: false: not blocked. true: blocked",
		//	      "type": "boolean"
		//	    },
		//	    "KubeletConfig": {
		//	      "description": "Kubelet component configuration",
		//	      "properties": {
		//	        "CpuManagerPolicy": {
		//	          "description": "Configure kubelet's CpuManagerPolicy. Includes none and static strategies",
		//	          "type": "string"
		//	        },
		//	        "FeatureGates": {
		//	          "description": "Feature gate.",
		//	          "properties": {
		//	            "InPlacePodVerticalScaling": {
		//	              "description": "Whether to enable the feature switch for local vertical Pod autoscaling",
		//	              "type": "boolean"
		//	            },
		//	            "QoSResourceManager": {
		//	              "description": "Enable QoSResourceManager feature switch. Options: - true to enable - false to disable",
		//	              "type": "boolean"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "KubeApiBurst": {
		//	          "description": "Maximum number of burst requests sent to the API server per second. Does not include events and node heartbeat APIs, whose rate limits are controlled by a different set of flags.",
		//	          "maximum": 100,
		//	          "minimum": 1,
		//	          "type": "integer"
		//	        },
		//	        "KubeApiQps": {
		//	          "description": "Queries per second (QPS) for communication with apiserver. Does not include event and node heartbeat APIs; their rate limits are controlled by a different set of flags",
		//	          "maximum": 50,
		//	          "minimum": 1,
		//	          "type": "integer"
		//	        },
		//	        "KubeReserved": {
		//	          "description": "Resources reserved for Kubernetes system components on the node. By default, half of the default value in the node reserved resource policy is reserved",
		//	          "insertionOrder": false,
		//	          "items": {
		//	            "properties": {
		//	              "Name": {
		//	                "description": "Resource name. Values: cpu or memory",
		//	                "type": "string"
		//	              },
		//	              "Quantity": {
		//	                "description": "Specify the resource quantity. - For cpu, example value: 200m - For memory, example value: 1G",
		//	                "type": "string"
		//	              }
		//	            },
		//	            "type": "object"
		//	          },
		//	          "type": "array",
		//	          "uniqueItems": true
		//	        },
		//	        "MaxPods": {
		//	          "description": "Configure the maximum number of Pods supported by kubelet",
		//	          "type": "integer"
		//	        },
		//	        "RegistryBurst": {
		//	          "description": "Set the maximum number of burst image pulls. Temporarily allow the number of image pulls specified by this parameter, provided it does not exceed the RegistryPullQps setting",
		//	          "maximum": 100,
		//	          "minimum": 1,
		//	          "type": "integer"
		//	        },
		//	        "RegistryPullQps": {
		//	          "description": "Can be used to limit the QPS cap for the image repository",
		//	          "maximum": 50,
		//	          "minimum": 1,
		//	          "type": "integer"
		//	        },
		//	        "SerializeImagePulls": {
		//	          "description": "Pull images one by one",
		//	          "type": "boolean"
		//	        },
		//	        "SystemReserved": {
		//	          "description": "Resources reserved for the operating system on the node. By default, resources are reserved at half the default value specified in the node reserved resource policy.",
		//	          "insertionOrder": false,
		//	          "items": {
		//	            "properties": {
		//	              "Name": {
		//	                "description": "Resource name. Values: cpu or memory.",
		//	                "type": "string"
		//	              },
		//	              "Quantity": {
		//	                "description": "Resource quantity for the specified resource. - For cpu, example value: 200m - For memory, example value: 1G",
		//	                "type": "string"
		//	              }
		//	            },
		//	            "type": "object"
		//	          },
		//	          "type": "array",
		//	          "uniqueItems": true
		//	        },
		//	        "TopologyManagerPolicy": {
		//	          "description": "Topology management policy. Values: none: (default) topology management policy disabled. restricted: kubelet only accepts Pods that achieve optimal NUMA (Non-Uniform Memory Access) on requested resources. best-effort: kubelet prioritizes Pods that achieve NUMA on CPU and device resources. single-numa-node: kubelet only allows Pods that achieve NUMA on CPU and device resources within the same node.",
		//	          "type": "string"
		//	        },
		//	        "TopologyManagerScope": {
		//	          "description": "Resource granularity for topology management strategy. Values: container: resource alignment at container level. pod: resource alignment at Pod level",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "Labels": {
		//	      "description": "Kubernetes label information for node pool/node",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "properties": {
		//	          "Key": {
		//	            "description": "Label key.",
		//	            "type": "string"
		//	          },
		//	          "Value": {
		//	            "description": "Label value",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "NamePrefix": {
		//	      "description": "Prefix of the metadata name for node objects in Kubernetes.",
		//	      "type": "string"
		//	    },
		//	    "NameSuffix": {
		//	      "description": "Suffix of the metadata name for node objects in Kubernetes.",
		//	      "type": "string"
		//	    },
		//	    "NameUseHostname": {
		//	      "description": "Whether the metadata name of the node object in Kubernetes uses the ECS host name. Values: true: use ECS host name as node name. false: do not use ECS host name as node name",
		//	      "type": "boolean"
		//	    },
		//	    "Taints": {
		//	      "description": "Kubernetes taint information for the node pool/node",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "properties": {
		//	          "Effect": {
		//	            "description": "Taint effect. Values: NoSchedule (default): do not schedule. NoExecute: evict pods that do not tolerate the taint. PreferNoSchedule: avoid scheduling if possible.",
		//	            "enum": [
		//	              "NoSchedule",
		//	              "NoExecute",
		//	              "PreferNoSchedule",
		//	              ""
		//	            ],
		//	            "type": "string"
		//	          },
		//	          "Key": {
		//	            "description": "Taint key",
		//	            "type": "string"
		//	          },
		//	          "Value": {
		//	            "description": "Taint value",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"kubernetes_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: AutoSyncDisabled
				"auto_sync_disabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether to disable the automatic synchronization of label taints to existing nodes. Parameter value description: true: disabled, automatic synchronization is turned off. false: not disabled, automatic synchronization is turned on.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Cordon
				"cordon": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Node blocking configuration. Parameter value description: false: not blocked. true: blocked",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: KubeletConfig
				"kubelet_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: CpuManagerPolicy
						"cpu_manager_policy": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Configure kubelet's CpuManagerPolicy. Includes none and static strategies",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: FeatureGates
						"feature_gates": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: InPlacePodVerticalScaling
								"in_place_pod_vertical_scaling": schema.BoolAttribute{ /*START ATTRIBUTE*/
									Description: "Whether to enable the feature switch for local vertical Pod autoscaling",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: QoSResourceManager
								"qo_s_resource_manager": schema.BoolAttribute{ /*START ATTRIBUTE*/
									Description: "Enable QoSResourceManager feature switch. Options:   - true to enable   - false to disable",
									Computed:    true,
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
							Description: "Feature gate.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: KubeApiBurst
						"kube_api_burst": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Maximum number of burst requests sent to the API server per second. Does not include events and node heartbeat APIs, whose rate limits are controlled by a different set of flags.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: KubeApiQps
						"kube_api_qps": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Queries per second (QPS) for communication with apiserver. Does not include event and node heartbeat APIs; their rate limits are controlled by a different set of flags",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: KubeReserved
						"kube_reserved": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
							NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
								Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
									// Property: Name
									"name": schema.StringAttribute{ /*START ATTRIBUTE*/
										Description: "Resource name. Values: cpu or memory",
										Computed:    true,
									}, /*END ATTRIBUTE*/
									// Property: Quantity
									"quantity": schema.StringAttribute{ /*START ATTRIBUTE*/
										Description: "Specify the resource quantity.   - For cpu, example value: 200m   - For memory, example value: 1G",
										Computed:    true,
									}, /*END ATTRIBUTE*/
								}, /*END SCHEMA*/
							}, /*END NESTED OBJECT*/
							Description: "Resources reserved for Kubernetes system components on the node. By default, half of the default value in the node reserved resource policy is reserved",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: MaxPods
						"max_pods": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Configure the maximum number of Pods supported by kubelet",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: RegistryBurst
						"registry_burst": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Set the maximum number of burst image pulls. Temporarily allow the number of image pulls specified by this parameter, provided it does not exceed the RegistryPullQps setting",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: RegistryPullQps
						"registry_pull_qps": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Can be used to limit the QPS cap for the image repository",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SerializeImagePulls
						"serialize_image_pulls": schema.BoolAttribute{ /*START ATTRIBUTE*/
							Description: "Pull images one by one",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SystemReserved
						"system_reserved": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
							NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
								Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
									// Property: Name
									"name": schema.StringAttribute{ /*START ATTRIBUTE*/
										Description: "Resource name. Values: cpu or memory.",
										Computed:    true,
									}, /*END ATTRIBUTE*/
									// Property: Quantity
									"quantity": schema.StringAttribute{ /*START ATTRIBUTE*/
										Description: "Resource quantity for the specified resource.   - For cpu, example value: 200m   - For memory, example value: 1G",
										Computed:    true,
									}, /*END ATTRIBUTE*/
								}, /*END SCHEMA*/
							}, /*END NESTED OBJECT*/
							Description: "Resources reserved for the operating system on the node. By default, resources are reserved at half the default value specified in the node reserved resource policy.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: TopologyManagerPolicy
						"topology_manager_policy": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Topology management policy. Values: none: (default) topology management policy disabled. restricted: kubelet only accepts Pods that achieve optimal NUMA (Non-Uniform Memory Access) on requested resources. best-effort: kubelet prioritizes Pods that achieve NUMA on CPU and device resources. single-numa-node: kubelet only allows Pods that achieve NUMA on CPU and device resources within the same node.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: TopologyManagerScope
						"topology_manager_scope": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Resource granularity for topology management strategy. Values: container: resource alignment at container level. pod: resource alignment at Pod level",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "Kubelet component configuration",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Labels
				"labels": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Key
							"key": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Label key.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Value
							"value": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Label value",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Kubernetes label information for node pool/node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NamePrefix
				"name_prefix": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Prefix of the metadata name for node objects in Kubernetes.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NameSuffix
				"name_suffix": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Suffix of the metadata name for node objects in Kubernetes.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NameUseHostname
				"name_use_hostname": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether the metadata name of the node object in Kubernetes uses the ECS host name. Values: true: use ECS host name as node name. false: do not use ECS host name as node name",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Taints
				"taints": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Effect
							"effect": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Taint effect. Values: NoSchedule (default): do not schedule. NoExecute: evict pods that do not tolerate the taint. PreferNoSchedule: avoid scheduling if possible.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Key
							"key": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Taint key",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Value
							"value": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Taint value",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Kubernetes taint information for the node pool/node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Kubernetes-related configuration for the node pool",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Management
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Managed node pool configuration",
		//	  "properties": {
		//	    "Enabled": {
		//	      "description": "Whether managed mode is enabled for the node pool. Values: - true: enabled - false: disabled",
		//	      "type": "boolean"
		//	    },
		//	    "RemedyConfig": {
		//	      "description": "Check self-healing configuration.",
		//	      "properties": {
		//	        "Enabled": {
		//	          "description": "Enable self-healing check",
		//	          "type": "boolean"
		//	        },
		//	        "RemedyId": {
		//	          "description": "Self-healing rule ID",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"management": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Enabled
				"enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether managed mode is enabled for the node pool. Values:   - true: enabled   - false: disabled",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: RemedyConfig
				"remedy_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: Enabled
						"enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
							Description: "Enable self-healing check",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: RemedyId
						"remedy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Self-healing rule ID",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "Check self-healing configuration.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Managed node pool configuration",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool name. Must be unique within the same cluster. Supports uppercase and lowercase English letters, Chinese characters, numbers, and hyphens (-). Length: 2–64 characters",
		//	  "maxLength": 64,
		//	  "minLength": 2,
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Node pool name. Must be unique within the same cluster. Supports uppercase and lowercase English letters, Chinese characters, numbers, and hyphens (-). Length: 2–64 characters",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodeConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Cloud server (ECS) instance configuration in the node pool",
		//	  "properties": {
		//	    "AdditionalContainerStorageEnabled": {
		//	      "description": "Whether the first data disk on the node has been configured, formatted, and mounted as the storage directory for container images and logs. Parameter values: false: not configured and formatted true: configured and formatted",
		//	      "type": "boolean"
		//	    },
		//	    "AutoRenew": {
		//	      "description": "Whether the cloud server instance is automatically renewed upon expiration. Parameter values: true: auto renewal false: no auto renewal This parameter is returned only when InstanceChargeType=PrePaid.",
		//	      "type": "boolean"
		//	    },
		//	    "AutoRenewPeriod": {
		//	      "description": "Automatic renewal duration for cloud server instance, in months. This parameter is returned only when AutoRenew=true.",
		//	      "type": "integer"
		//	    },
		//	    "DataVolumes": {
		//	      "description": "Data disk configuration for the node",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "properties": {
		//	          "FileSystem": {
		//	            "description": "File system. Options: - Ext4 (default) - Xfs",
		//	            "type": "string"
		//	          },
		//	          "MountPoint": {
		//	            "description": "Target mount directory after disk formatting.",
		//	            "type": "string"
		//	          },
		//	          "PlacementGroupId": {
		//	            "description": "Placement group ID",
		//	            "type": "string"
		//	          },
		//	          "Size": {
		//	            "description": "Disk capacity, in GiB",
		//	            "type": "integer"
		//	          },
		//	          "SnapshotId": {
		//	            "description": "Create a data disk using a snapshot. You can call the DescribeSnapshots API to query the snapshot ID. Note: Only ultra-fast SSD and efficient cloud disks support creating disks from snapshots. Only snapshots in 'available' status can be used to create new disks; snapshots in 'creating', 'rolling back', 'deleting', or 'error' status cannot be used to create new disks",
		//	            "type": "string"
		//	          },
		//	          "SubgroupNumber": {
		//	            "description": "Placement subgroup",
		//	            "type": "integer"
		//	          },
		//	          "Type": {
		//	            "description": "Disk type: ESSD_PL0: ultra-fast SSD cloud disk with performance level PL0. ESSD_FlexPL: ultra-fast SSD cloud disk with performance level PL1.",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "DeploymentSetGroupNumber": {
		//	      "description": "Group number of the instance in the deployment set. 0 means not set",
		//	      "type": "integer"
		//	    },
		//	    "DeploymentSetId": {
		//	      "description": "Deployment set ID to be added to the instance",
		//	      "type": "string"
		//	    },
		//	    "Hostname": {
		//	      "description": "Host name corresponding to the node",
		//	      "type": "string"
		//	    },
		//	    "HpcClusterIds": {
		//	      "description": "High performance computing cluster ID. When the node pool is configured with high performance computing GPU node types, returns the high performance computing cluster ID",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "ImageId": {
		//	      "description": "Image ID used by the cloud server corresponding to the node",
		//	      "type": "string"
		//	    },
		//	    "InitializeScript": {
		//	      "description": "Custom script executed after creating and initializing the node. Shell script in Base64 encoding",
		//	      "type": "string"
		//	    },
		//	    "InstanceChargeType": {
		//	      "description": "Billing type for cloud server instance. Parameter value description: PostPaid: pay-as-you-go. PrePaid: subscription (annual/monthly).",
		//	      "type": "string"
		//	    },
		//	    "InstanceName": {
		//	      "description": "Node (instance) name",
		//	      "type": "string"
		//	    },
		//	    "InstanceTypeIds": {
		//	      "description": "List of cloud server instance type IDs corresponding to the node",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "InstancesDistribution": {
		//	      "description": "Configure the mixed strategy for spot and pay-as-you-go instances. This strategy takes effect when SpotStrategy is set to SpotAsPriceGo",
		//	      "properties": {
		//	        "CapacityRebalance": {
		//	          "description": "Capacity rebalancing. Value range: - true: enables this feature. When a preemptible instance is about to be reclaimed, a new preemptible instance is proactively created for compensation. - false (default): disables this feature. Waits until the preemptible instance is reclaimed before scaling out to make up the instance count.",
		//	          "type": "boolean"
		//	        },
		//	        "CompensateWithOnDemand": {
		//	          "description": "Pay-as-you-go instance fallback feature. Value range: - true: enables this feature. If all preemptible instances fail to purchase due to insufficient inventory, pay-as-you-go instances will be attempted - false (default): disables this feature. When scaling preemptible instances, only the configured preemptible instances are attempted",
		//	          "type": "boolean"
		//	        },
		//	        "OnDemandBaseCapacity": {
		//	          "description": "Base capacity size. The base capacity is always pay-as-you-go instances. Value range: [0,500], default: 0",
		//	          "type": "integer"
		//	        },
		//	        "OnDemandPercentageAboveBaseCapacity": {
		//	          "description": "Proportion of pay-as-you-go instances for capacity exceeding the base capacity. Value range [0, 100]. 0 means only preemptible instances are produced for excess capacity; 100 means only pay-as-you-go instances are produced. Default is 0.",
		//	          "type": "integer"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "NamePrefix": {
		//	      "description": "Node name prefix. An empty string or nil means the node name prefix policy is not enabled",
		//	      "type": "string"
		//	    },
		//	    "NetworkTrafficMode": {
		//	      "description": "Network communication mode between nodes",
		//	      "type": "string"
		//	    },
		//	    "Period": {
		//	      "description": "Duration for purchasing cloud server instance, in months. This parameter is returned only when InstanceChargeType=PrePaid",
		//	      "type": "integer"
		//	    },
		//	    "PreScript": {
		//	      "description": "Script executed before deploying nodes",
		//	      "type": "string"
		//	    },
		//	    "ProjectName": {
		//	      "description": "The project to which the ECS belongs. Each ECS can only belong to one project.",
		//	      "type": "string"
		//	    },
		//	    "PublicAccessConfig": {
		//	      "description": "Configuration for automatic public network access for nodes",
		//	      "properties": {
		//	        "Bandwidth": {
		//	          "description": "Peak bandwidth for the public IP, unit: Mbps",
		//	          "type": "integer"
		//	        },
		//	        "BillingType": {
		//	          "description": "Billing type for public IP: 2: Pay-as-you-go by bandwidth cap. 3: Pay-as-you-go by actual traffic.",
		//	          "type": "integer"
		//	        },
		//	        "Isp": {
		//	          "description": "Public IP line type. Parameter description: BGP: BGP (multi-line)",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "PublicAccessEnabled": {
		//	      "description": "Whether the node automatically enables public network access. Values: - false: disabled - true: enabled",
		//	      "type": "boolean"
		//	    },
		//	    "Security": {
		//	      "description": "Node security configuration.",
		//	      "properties": {
		//	        "Login": {
		//	          "description": "Node access configuration",
		//	          "properties": {
		//	            "Password": {
		//	              "description": "Root user login password in Base64 encoding. Follow the cloud server password requirements: 8–30 characters, cannot start with / or $6$, must include at least three of the following: lowercase letters a–z, uppercase letters A–Z, numbers 0–9, special characters ( ) ` ~ ! @ # $ % ^ \u0026 * _ - + = | { } [ ] : ; ' \u003c \u003e , . ? /",
		//	              "type": "string"
		//	            },
		//	            "SshKeyPairName": {
		//	              "description": "SSH key pair name. Please ensure the key pair is already created or hosted in the cloud server",
		//	              "type": "string"
		//	            },
		//	            "Type": {
		//	              "description": "Node access login method. Parameter value description: Password: password login. SshKeyPair: SSH key pair login.",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "SecurityGroupIds": {
		//	          "description": "List of security group IDs for the node network",
		//	          "insertionOrder": false,
		//	          "items": {
		//	            "type": "string"
		//	          },
		//	          "type": "array",
		//	          "uniqueItems": true
		//	        },
		//	        "SecurityStrategies": {
		//	          "description": "Node security policy. Parameter value description: Hids: host security hardening",
		//	          "insertionOrder": false,
		//	          "items": {
		//	            "type": "string"
		//	          },
		//	          "type": "array",
		//	          "uniqueItems": true
		//	        },
		//	        "SecurityStrategyEnabled": {
		//	          "description": "Whether security hardening is enabled for the node. Parameter value description: true: enabled. false: not enabled.",
		//	          "type": "boolean"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "SpotStrategy": {
		//	      "description": "Preemptive policy for pay-as-you-go billing. When InstanceChargeType=PostPaid: NoSpot: regular pay-as-you-go instance. SpotAsPriceGo: system auto-bidding, follows current market price.",
		//	      "type": "string"
		//	    },
		//	    "SubnetIds": {
		//	      "description": "List of subnet IDs to which the node network belongs.",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "type": "string"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "SystemVolume": {
		//	      "description": "System disk configuration for the node",
		//	      "properties": {
		//	        "PlacementGroupId": {
		//	          "description": "Placement group ID",
		//	          "type": "string"
		//	        },
		//	        "Size": {
		//	          "description": "Cloud disk capacity, in GiB. Value description: default: 40 GiB. Ultra-fast SSD (ESSD_PL0, ESSD_FlexPL): 40–2048 GiB",
		//	          "type": "integer"
		//	        },
		//	        "SubgroupNumber": {
		//	          "description": "Placement subgroup",
		//	          "type": "integer"
		//	        },
		//	        "Type": {
		//	          "description": "Cloud disk type: ESSD_PL0: (default) Ultra SSD with performance level PL0. ESSD_FlexPL: Ultra SSD with performance level PL1",
		//	          "type": "string"
		//	        }
		//	      },
		//	      "type": "object"
		//	    },
		//	    "Tags": {
		//	      "description": "Label information configured for the node pool",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "properties": {
		//	          "Key": {
		//	            "description": "Label key.",
		//	            "type": "string"
		//	          },
		//	          "Value": {
		//	            "description": "Tag value",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "required": [
		//	          "Key"
		//	        ],
		//	        "type": "object"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"node_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: AdditionalContainerStorageEnabled
				"additional_container_storage_enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether the first data disk on the node has been configured, formatted, and mounted as the storage directory for container images and logs. Parameter values: false: not configured and formatted true: configured and formatted",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: AutoRenew
				"auto_renew": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether the cloud server instance is automatically renewed upon expiration. Parameter values: true: auto renewal false: no auto renewal This parameter is returned only when InstanceChargeType=PrePaid.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: AutoRenewPeriod
				"auto_renew_period": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Automatic renewal duration for cloud server instance, in months. This parameter is returned only when AutoRenew=true.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: DataVolumes
				"data_volumes": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: FileSystem
							"file_system": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "File system. Options:   - Ext4 (default)   - Xfs",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: MountPoint
							"mount_point": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Target mount directory after disk formatting.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: PlacementGroupId
							"placement_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Placement group ID",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Size
							"size": schema.Int64Attribute{ /*START ATTRIBUTE*/
								Description: "Disk capacity, in GiB",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: SnapshotId
							"snapshot_id": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Create a data disk using a snapshot. You can call the DescribeSnapshots API to query the snapshot ID. Note: Only ultra-fast SSD and efficient cloud disks support creating disks from snapshots. Only snapshots in 'available' status can be used to create new disks; snapshots in 'creating', 'rolling back', 'deleting', or 'error' status cannot be used to create new disks",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: SubgroupNumber
							"subgroup_number": schema.Int64Attribute{ /*START ATTRIBUTE*/
								Description: "Placement subgroup",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Type
							"type": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Disk type: ESSD_PL0: ultra-fast SSD cloud disk with performance level PL0. ESSD_FlexPL: ultra-fast SSD cloud disk with performance level PL1.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Data disk configuration for the node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: DeploymentSetGroupNumber
				"deployment_set_group_number": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Group number of the instance in the deployment set. 0 means not set",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: DeploymentSetId
				"deployment_set_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Deployment set ID to be added to the instance",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Hostname
				"hostname": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Host name corresponding to the node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: HpcClusterIds
				"hpc_cluster_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "High performance computing cluster ID. When the node pool is configured with high performance computing GPU node types, returns the high performance computing cluster ID",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ImageId
				"image_id": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Image ID used by the cloud server corresponding to the node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InitializeScript
				"initialize_script": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Custom script executed after creating and initializing the node. Shell script in Base64 encoding",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InstanceChargeType
				"instance_charge_type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Billing type for cloud server instance. Parameter value description: PostPaid: pay-as-you-go. PrePaid: subscription (annual/monthly).",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InstanceName
				"instance_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Node (instance) name",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InstanceTypeIds
				"instance_type_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "List of cloud server instance type IDs corresponding to the node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InstancesDistribution
				"instances_distribution": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: CapacityRebalance
						"capacity_rebalance": schema.BoolAttribute{ /*START ATTRIBUTE*/
							Description: "Capacity rebalancing. Value range:   - true: enables this feature. When a preemptible instance is about to be reclaimed, a new preemptible instance is proactively created for compensation.   - false (default): disables this feature. Waits until the preemptible instance is reclaimed before scaling out to make up the instance count.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: CompensateWithOnDemand
						"compensate_with_on_demand": schema.BoolAttribute{ /*START ATTRIBUTE*/
							Description: "Pay-as-you-go instance fallback feature. Value range:   - true: enables this feature. If all preemptible instances fail to purchase due to insufficient inventory, pay-as-you-go instances will be attempted   - false (default): disables this feature. When scaling preemptible instances, only the configured preemptible instances are attempted",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: OnDemandBaseCapacity
						"on_demand_base_capacity": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Base capacity size. The base capacity is always pay-as-you-go instances. Value range: [0,500], default: 0",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: OnDemandPercentageAboveBaseCapacity
						"on_demand_percentage_above_base_capacity": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Proportion of pay-as-you-go instances for capacity exceeding the base capacity. Value range [0, 100]. 0 means only preemptible instances are produced for excess capacity; 100 means only pay-as-you-go instances are produced. Default is 0.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "Configure the mixed strategy for spot and pay-as-you-go instances. This strategy takes effect when SpotStrategy is set to SpotAsPriceGo",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NamePrefix
				"name_prefix": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Node name prefix. An empty string or nil means the node name prefix policy is not enabled",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: NetworkTrafficMode
				"network_traffic_mode": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Network communication mode between nodes",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Period
				"period": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Duration for purchasing cloud server instance, in months. This parameter is returned only when InstanceChargeType=PrePaid",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: PreScript
				"pre_script": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Script executed before deploying nodes",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ProjectName
				"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "The project to which the ECS belongs. Each ECS can only belong to one project.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: PublicAccessConfig
				"public_access_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: Bandwidth
						"bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Peak bandwidth for the public IP, unit: Mbps",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: BillingType
						"billing_type": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Billing type for public IP: 2: Pay-as-you-go by bandwidth cap. 3: Pay-as-you-go by actual traffic.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: Isp
						"isp": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Public IP line type. Parameter description: BGP: BGP (multi-line)",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "Configuration for automatic public network access for nodes",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: PublicAccessEnabled
				"public_access_enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Whether the node automatically enables public network access. Values:   - false: disabled   - true: enabled",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Security
				"security": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: Login
						"login": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: Password
								"password": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Root user login password in Base64 encoding. Follow the cloud server password requirements: 8–30 characters, cannot start with / or $6$, must include at least three of the following: lowercase letters a–z, uppercase letters A–Z, numbers 0–9, special characters ( ) ` ~ ! @ # $ % ^ & * _   - + = | { } [ ] : ; ' < > , . ? /",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: SshKeyPairName
								"ssh_key_pair_name": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "SSH key pair name. Please ensure the key pair is already created or hosted in the cloud server",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: Type
								"type": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Node access login method. Parameter value description: Password: password login. SshKeyPair: SSH key pair login.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
							Description: "Node access configuration",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SecurityGroupIds
						"security_group_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
							ElementType: types.StringType,
							Description: "List of security group IDs for the node network",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SecurityStrategies
						"security_strategies": schema.SetAttribute{ /*START ATTRIBUTE*/
							ElementType: types.StringType,
							Description: "Node security policy. Parameter value description: Hids: host security hardening",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SecurityStrategyEnabled
						"security_strategy_enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
							Description: "Whether security hardening is enabled for the node. Parameter value description: true: enabled. false: not enabled.",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "Node security configuration.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SpotStrategy
				"spot_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Preemptive policy for pay-as-you-go billing. When InstanceChargeType=PostPaid: NoSpot: regular pay-as-you-go instance. SpotAsPriceGo: system auto-bidding, follows current market price.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SubnetIds
				"subnet_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
					ElementType: types.StringType,
					Description: "List of subnet IDs to which the node network belongs.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: SystemVolume
				"system_volume": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
					Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
						// Property: PlacementGroupId
						"placement_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Placement group ID",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: Size
						"size": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Cloud disk capacity, in GiB. Value description: default: 40 GiB. Ultra-fast SSD (ESSD_PL0, ESSD_FlexPL): 40–2048 GiB",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: SubgroupNumber
						"subgroup_number": schema.Int64Attribute{ /*START ATTRIBUTE*/
							Description: "Placement subgroup",
							Computed:    true,
						}, /*END ATTRIBUTE*/
						// Property: Type
						"type": schema.StringAttribute{ /*START ATTRIBUTE*/
							Description: "Cloud disk type: ESSD_PL0: (default) Ultra SSD with performance level PL0. ESSD_FlexPL: Ultra SSD with performance level PL1",
							Computed:    true,
						}, /*END ATTRIBUTE*/
					}, /*END SCHEMA*/
					Description: "System disk configuration for the node",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Tags
				"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Key
							"key": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Label key.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Value
							"value": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Tag value",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Label information configured for the node pool",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Cloud server (ECS) instance configuration in the node pool",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodePoolId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool ID",
		//	  "type": "string"
		//	}
		"node_pool_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Node pool ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodeStatistics
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node statistics in the node pool.",
		//	  "properties": {
		//	    "CreatingCount": {
		//	      "description": "Total number of nodes with Phase=Creating.",
		//	      "type": "integer"
		//	    },
		//	    "DeletingCount": {
		//	      "description": "Total number of nodes with Phase=Deleting.",
		//	      "type": "integer"
		//	    },
		//	    "FailedCount": {
		//	      "description": "Total number of nodes with Phase=Failed",
		//	      "type": "integer"
		//	    },
		//	    "RunningCount": {
		//	      "description": "Total number of nodes with Phase=Running",
		//	      "type": "integer"
		//	    },
		//	    "TotalCount": {
		//	      "description": "Total number of nodes in the node pool.",
		//	      "type": "integer"
		//	    },
		//	    "UpdatingCount": {
		//	      "description": "Total number of nodes with Phase=Updating",
		//	      "type": "integer"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"node_statistics": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: CreatingCount
				"creating_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes with Phase=Creating.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: DeletingCount
				"deleting_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes with Phase=Deleting.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: FailedCount
				"failed_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes with Phase=Failed",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: RunningCount
				"running_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes with Phase=Running",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: TotalCount
				"total_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes in the node pool.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: UpdatingCount
				"updating_count": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Total number of nodes with Phase=Updating",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Node statistics in the node pool.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool status",
		//	  "properties": {
		//	    "Conditions": {
		//	      "description": "Status conditions of the node pool in its current primary state, indicating the reason for entering this state",
		//	      "insertionOrder": false,
		//	      "items": {
		//	        "properties": {
		//	          "Type": {
		//	            "description": "Status conditions under the current primary state of the node pool, indicating the reasons for entering this state. There can be multiple reasons. Parameter values: ProgressingOk, ResourceCleanupFailed, Unknown, ClusterNotRunning.",
		//	            "type": "string"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array",
		//	      "uniqueItems": true
		//	    },
		//	    "Phase": {
		//	      "description": "Status of the node pool. Parameter values: Creating, Running, Updating, Deleting, Failed, Scaling.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"status": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Conditions
				"conditions": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: Type
							"type": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Status conditions under the current primary state of the node pool, indicating the reasons for entering this state. There can be multiple reasons. Parameter values: ProgressingOk, ResourceCleanupFailed, Unknown, ClusterNotRunning.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Status conditions of the node pool in its current primary state, indicating the reason for entering this state",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Phase
				"phase": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Status of the node pool. Parameter values: Creating, Running, Updating, Deleting, Failed, Scaling.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Node pool status",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Node pool tag information",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Label key.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Label key.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Node pool tag information",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Time when the node pool was updated",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Time when the node pool was updated",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VKE::DefaultNodePool",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VKE::DefaultNodePool").WithTerraformTypeName("volcenginecc_vke_default_node_pool")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"additional_container_storage_enabled": "AdditionalContainerStorageEnabled",
		"auto_renew":                           "AutoRenew",
		"auto_renew_period":                    "AutoRenewPeriod",
		"auto_scaling":                         "AutoScaling",
		"auto_sync_disabled":                   "AutoSyncDisabled",
		"bandwidth":                            "Bandwidth",
		"billing_type":                         "BillingType",
		"capacity_rebalance":                   "CapacityRebalance",
		"cluster_id":                           "ClusterId",
		"compensate_with_on_demand":            "CompensateWithOnDemand",
		"conditions":                           "Conditions",
		"cordon":                               "Cordon",
		"cpu_manager_policy":                   "CpuManagerPolicy",
		"created_time":                         "CreatedTime",
		"creating_count":                       "CreatingCount",
		"data_volumes":                         "DataVolumes",
		"deleting_count":                       "DeletingCount",
		"deployment_set_group_number":          "DeploymentSetGroupNumber",
		"deployment_set_id":                    "DeploymentSetId",
		"desired_replicas":                     "DesiredReplicas",
		"effect":                               "Effect",
		"enabled":                              "Enabled",
		"failed_count":                         "FailedCount",
		"feature_gates":                        "FeatureGates",
		"file_system":                          "FileSystem",
		"hostname":                             "Hostname",
		"hpc_cluster_ids":                      "HpcClusterIds",
		"image_id":                             "ImageId",
		"in_place_pod_vertical_scaling":        "InPlacePodVerticalScaling",
		"initialize_script":                    "InitializeScript",
		"instance_charge_type":                 "InstanceChargeType",
		"instance_name":                        "InstanceName",
		"instance_type_ids":                    "InstanceTypeIds",
		"instances_distribution":               "InstancesDistribution",
		"isp":                                  "Isp",
		"key":                                  "Key",
		"kube_api_burst":                       "KubeApiBurst",
		"kube_api_qps":                         "KubeApiQps",
		"kube_reserved":                        "KubeReserved",
		"kubelet_config":                       "KubeletConfig",
		"kubernetes_config":                    "KubernetesConfig",
		"labels":                               "Labels",
		"login":                                "Login",
		"management":                           "Management",
		"max_pods":                             "MaxPods",
		"max_replicas":                         "MaxReplicas",
		"min_replicas":                         "MinReplicas",
		"mount_point":                          "MountPoint",
		"name":                                 "Name",
		"name_prefix":                          "NamePrefix",
		"name_suffix":                          "NameSuffix",
		"name_use_hostname":                    "NameUseHostname",
		"network_traffic_mode":                 "NetworkTrafficMode",
		"node_config":                          "NodeConfig",
		"node_pool_id":                         "NodePoolId",
		"node_statistics":                      "NodeStatistics",
		"on_demand_base_capacity":              "OnDemandBaseCapacity",
		"on_demand_percentage_above_base_capacity": "OnDemandPercentageAboveBaseCapacity",
		"password":                  "Password",
		"period":                    "Period",
		"phase":                     "Phase",
		"placement_group_id":        "PlacementGroupId",
		"pre_script":                "PreScript",
		"priority":                  "Priority",
		"project_name":              "ProjectName",
		"public_access_config":      "PublicAccessConfig",
		"public_access_enabled":     "PublicAccessEnabled",
		"qo_s_resource_manager":     "QoSResourceManager",
		"quantity":                  "Quantity",
		"registry_burst":            "RegistryBurst",
		"registry_pull_qps":         "RegistryPullQps",
		"remedy_config":             "RemedyConfig",
		"remedy_id":                 "RemedyId",
		"running_count":             "RunningCount",
		"scaling_group_id":          "ScalingGroupId",
		"security":                  "Security",
		"security_group_ids":        "SecurityGroupIds",
		"security_strategies":       "SecurityStrategies",
		"security_strategy_enabled": "SecurityStrategyEnabled",
		"serialize_image_pulls":     "SerializeImagePulls",
		"size":                      "Size",
		"snapshot_id":               "SnapshotId",
		"spot_strategy":             "SpotStrategy",
		"ssh_key_pair_name":         "SshKeyPairName",
		"status":                    "Status",
		"subgroup_number":           "SubgroupNumber",
		"subnet_ids":                "SubnetIds",
		"subnet_policy":             "SubnetPolicy",
		"system_reserved":           "SystemReserved",
		"system_volume":             "SystemVolume",
		"tags":                      "Tags",
		"taints":                    "Taints",
		"topology_manager_policy":   "TopologyManagerPolicy",
		"topology_manager_scope":    "TopologyManagerScope",
		"total_count":               "TotalCount",
		"type":                      "Type",
		"updated_time":              "UpdatedTime",
		"updating_count":            "UpdatingCount",
		"value":                     "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
