// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package clb

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_clb_nlb_listener", nLBListenerDataSource)
}

// nLBListenerDataSource returns the Terraform volcenginecc_clb_nlb_listener data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::CLB::NLBListener resource.
func nLBListenerDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CertificateId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "TLS listener server certificate ID. Only SSL certificates from the certificate center are supported.",
		//	  "type": "string"
		//	}
		"certificate_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "TLS listener server certificate ID. Only SSL certificates from the certificate center are supported.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ConnectionTimeout
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener connection timeout (seconds)",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"connection_timeout": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Listener connection timeout (seconds)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener creation time",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener creation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener description",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Enabled
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener enabled: true (enabled); false (disabled)",
		//	  "type": "boolean"
		//	}
		"enabled": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Listener enabled: true (enabled); false (disabled)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: EndPort
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "End port for all-port listening. Valid only when Port is 0.",
		//	  "format": "int64",
		//	  "maximum": 65535,
		//	  "minimum": 1,
		//	  "type": "integer"
		//	}
		"end_port": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "End port for all-port listening. Valid only when Port is 0.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Health
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Backend instance health check response information",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "InstanceId": {
		//	        "description": "Backend server instance ID or IP address",
		//	        "type": "string"
		//	      },
		//	      "Ip": {
		//	        "description": "Backend server IP address",
		//	        "type": "string"
		//	      },
		//	      "Port": {
		//	        "description": "Port on which the backend server provides services",
		//	        "format": "int64",
		//	        "maximum": 65535,
		//	        "minimum": 1,
		//	        "type": "integer"
		//	      },
		//	      "ServerId": {
		//	        "description": "Backend server ID",
		//	        "type": "string"
		//	      },
		//	      "ServerType": {
		//	        "description": "Backend server type: ecs (cloud server instance, i.e., primary network interface); eni (secondary network interface); ip (IP address)",
		//	        "enum": [
		//	          "ecs",
		//	          "eni",
		//	          "ip"
		//	        ],
		//	        "type": "string"
		//	      },
		//	      "Status": {
		//	        "description": "Backend server health status: Up (normal); Down (abnormal); Unused (not in use—NLB instance has disabled cross-zone forwarding and there is no traffic from this backend server's zone)",
		//	        "enum": [
		//	          "Up",
		//	          "Down",
		//	          "Unused"
		//	        ],
		//	        "type": "string"
		//	      },
		//	      "UpdatedTime": {
		//	        "description": "Last update time of health status",
		//	        "type": "string"
		//	      },
		//	      "ZoneId": {
		//	        "description": "Zone ID where the backend server receives traffic",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"health": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: InstanceId
					"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Backend server instance ID or IP address",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Ip
					"ip": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Backend server IP address",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Port
					"port": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Port on which the backend server provides services",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ServerId
					"server_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Backend server ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ServerType
					"server_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Backend server type: ecs (cloud server instance, i.e., primary network interface); eni (secondary network interface); ip (IP address)",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Status
					"status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Backend server health status: Up (normal); Down (abnormal); Unused (not in use—NLB instance has disabled cross-zone forwarding and there is no traffic from this backend server's zone)",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: UpdatedTime
					"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Last update time of health status",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ZoneId
					"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Zone ID where the backend server receives traffic",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Backend instance health check response information",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ListenerId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener unique identifier",
		//	  "type": "string"
		//	}
		"listener_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener unique identifier",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ListenerName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener name",
		//	  "type": "string"
		//	}
		"listener_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: LoadBalancerId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Load balancer instance ID",
		//	  "type": "string"
		//	}
		"load_balancer_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Load balancer instance ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Port
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Port on which the listener receives requests. 0 indicates all-port listening is enabled.",
		//	  "format": "int64",
		//	  "maximum": 65535,
		//	  "minimum": 0,
		//	  "type": "integer"
		//	}
		"port": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Port on which the listener receives requests. 0 indicates all-port listening is enabled.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Protocol
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener protocol type: TCP, UDP, TLS",
		//	  "enum": [
		//	    "TCP",
		//	    "UDP",
		//	    "TLS"
		//	  ],
		//	  "type": "string"
		//	}
		"protocol": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener protocol type: TCP, UDP, TLS",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SecurityPolicyId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "TLS security policy ID. Supports both system security policies and custom security policies. System security policy values: .tls_cipher_policy_1_0 .tls_cipher_policy_1_1 .tls_cipher_policy_1_2 .tls_cipher_policy_1_2_strict .tls_cipher_policy_1_2_strict_with_1_3. For custom security policies, enter the custom security policy ID. This parameter is required when Protocol is TLS.",
		//	  "type": "string"
		//	}
		"security_policy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "TLS security policy ID. Supports both system security policies and custom security policies. System security policy values: .tls_cipher_policy_1_0 .tls_cipher_policy_1_1 .tls_cipher_policy_1_2 .tls_cipher_policy_1_2_strict .tls_cipher_policy_1_2_strict_with_1_3. For custom security policies, enter the custom security policy ID. This parameter is required when Protocol is TLS.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ServerGroupId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Server group ID associated with the listener",
		//	  "type": "string"
		//	}
		"server_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Server group ID associated with the listener",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StartPort
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Start port for all-port listening. Valid only when Port is 0.",
		//	  "format": "int64",
		//	  "maximum": 65535,
		//	  "minimum": 1,
		//	  "type": "integer"
		//	}
		"start_port": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Start port for all-port listening. Valid only when Port is 0.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener status",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener status",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Resource tags",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key",
		//	      "Value"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Resource tags",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Listener's most recent operation time",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Listener's most recent operation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::CLB::NLBListener",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CLB::NLBListener").WithTerraformTypeName("volcenginecc_clb_nlb_listener")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"certificate_id":     "CertificateId",
		"connection_timeout": "ConnectionTimeout",
		"created_time":       "CreatedTime",
		"description":        "Description",
		"enabled":            "Enabled",
		"end_port":           "EndPort",
		"health":             "Health",
		"instance_id":        "InstanceId",
		"ip":                 "Ip",
		"key":                "Key",
		"listener_id":        "ListenerId",
		"listener_name":      "ListenerName",
		"load_balancer_id":   "LoadBalancerId",
		"port":               "Port",
		"protocol":           "Protocol",
		"security_policy_id": "SecurityPolicyId",
		"server_group_id":    "ServerGroupId",
		"server_id":          "ServerId",
		"server_type":        "ServerType",
		"start_port":         "StartPort",
		"status":             "Status",
		"tags":               "Tags",
		"updated_time":       "UpdatedTime",
		"value":              "Value",
		"zone_id":            "ZoneId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
