// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package efs

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_efs_file_system", fileSystemResource)
}

// fileSystemResource returns the Terraform volcenginecc_efs_file_system resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::EFS::FileSystem resource.
func fileSystemResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccessPointLimit
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "接入点上限。",
		//	  "format": "int32",
		//	  "type": "integer"
		//	}
		"access_point_limit": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "接入点上限。",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ChargeConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统计费配置。",
		//	  "properties": {
		//	    "ChargeStatus": {
		//	      "description": "计费状态，取值说明如下：WaitingPaid：等待支付,Pending：创建中,Modifying：更配中,Failed：失败,Normal：正常,Expired：过期,Overdue：欠费,Reclaimed：回收,Terminated：退订。",
		//	      "type": "string"
		//	    },
		//	    "ChargeType": {
		//	      "description": "计费类型。仅支持取值为PayAsYouGo，表示按量计费。",
		//	      "type": "string"
		//	    },
		//	    "ExpireTime": {
		//	      "description": "到期时间。",
		//	      "type": "string"
		//	    },
		//	    "ReclaimTime": {
		//	      "description": "回收时间。",
		//	      "type": "string"
		//	    },
		//	    "StopTime": {
		//	      "description": "关停时间。",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"charge_config": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: ChargeStatus
				"charge_status": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "计费状态，取值说明如下：WaitingPaid：等待支付,Pending：创建中,Modifying：更配中,Failed：失败,Normal：正常,Expired：过期,Overdue：欠费,Reclaimed：回收,Terminated：退订。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ChargeType
				"charge_type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "计费类型。仅支持取值为PayAsYouGo，表示按量计费。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ExpireTime
				"expire_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "到期时间。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ReclaimTime
				"reclaim_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "回收时间。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: StopTime
				"stop_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "关停时间。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "文件系统计费配置。",
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ChargeType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "计费类型。仅支持取值为PayAsYouGo，表示按量计费。",
		//	  "type": "string"
		//	}
		"charge_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "计费类型。仅支持取值为PayAsYouGo，表示按量计费。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// ChargeType is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统创建时间。",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统创建时间。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "描述信息。",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "描述信息。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: DowngradeUnlockTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统带宽可以降配的时间。",
		//	  "type": "string"
		//	}
		"downgrade_unlock_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统带宽可以降配的时间。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: FileSystemId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统 ID。",
		//	  "type": "string"
		//	}
		"file_system_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统 ID。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: FileSystemName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统名称。",
		//	  "type": "string"
		//	}
		"file_system_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统名称。",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Basic：基础型,Premium：高级型",
		//	  "type": "string"
		//	}
		"instance_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Basic：基础型,Premium：高级型",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: MountPointLimit
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "挂载点上限。",
		//	  "format": "int32",
		//	  "type": "integer"
		//	}
		"mount_point_limit": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "挂载点上限。",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Performance
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统性能信息。",
		//	  "properties": {
		//	    "BandwidthMode": {
		//	      "description": "带宽模式，取值说明如下：Baseline：基线带宽模式,Provisioned：预置带宽模式",
		//	      "type": "string"
		//	    },
		//	    "BaselineBandwidth": {
		//	      "description": "基准带宽。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    },
		//	    "BaselineIops": {
		//	      "description": "基准 IOPS。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    },
		//	    "BurstBandwidth": {
		//	      "description": "突发带宽。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    },
		//	    "BurstIops": {
		//	      "description": "突发 IOPS。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    },
		//	    "ProvisionedBandwidth": {
		//	      "description": "预置带宽。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    },
		//	    "ProvisionedIops": {
		//	      "description": "预置 IOPS。",
		//	      "format": "int32",
		//	      "type": "integer"
		//	    }
		//	  },
		//	  "required": [
		//	    "BandwidthMode"
		//	  ],
		//	  "type": "object"
		//	}
		"performance": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: BandwidthMode
				"bandwidth_mode": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "带宽模式，取值说明如下：Baseline：基线带宽模式,Provisioned：预置带宽模式",
					Required:    true,
				}, /*END ATTRIBUTE*/
				// Property: BaselineBandwidth
				"baseline_bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "基准带宽。",
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: BaselineIops
				"baseline_iops": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "基准 IOPS。",
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: BurstBandwidth
				"burst_bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "突发带宽。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: BurstIops
				"burst_iops": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "突发 IOPS。",
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: ProvisionedBandwidth
				"provisioned_bandwidth": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "预置带宽。",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: ProvisionedIops
				"provisioned_iops": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "预置 IOPS。",
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "文件系统性能信息。",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: PerformanceDensity
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统性能密度，取值说明如下：Basic_50：基础型 50MB/s/TiB,Premium_125：高级型 125MB/s/TiB。",
		//	  "type": "string"
		//	}
		"performance_density": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统性能密度，取值说明如下：Basic_50：基础型 50MB/s/TiB,Premium_125：高级型 125MB/s/TiB。",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "项目名称。",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "项目名称。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProtocolTypes
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "协议类型",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"protocol_types": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "协议类型",
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统状态。取值说明如下：Creating：创建中。CreateError：创建失败。Running：运行中。Updating：更新中。Deleting：删除中。DeleteError：删除失败。Deleted：已删除。Stopped：已关停。",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统状态。取值说明如下：Creating：创建中。CreateError：创建失败。Running：运行中。Updating：更新中。Deleting：删除中。DeleteError：删除失败。Deleted：已删除。Stopped：已关停。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Storage
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统容量信息。",
		//	  "properties": {
		//	    "CapacityLimit": {
		//	      "description": "容量上限，单位为 MiB。",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "CapacityUsed": {
		//	      "description": "已用容量，单位为 MiB。",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "InodeLimit": {
		//	      "description": "文件数上限。",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    },
		//	    "InodeUsed": {
		//	      "description": "已用文件数。",
		//	      "format": "int64",
		//	      "type": "integer"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"storage": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: CapacityLimit
				"capacity_limit": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "容量上限，单位为 MiB。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: CapacityUsed
				"capacity_used": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "已用容量，单位为 MiB。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InodeLimit
				"inode_limit": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "文件数上限。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: InodeUsed
				"inode_used": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "已用文件数。",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "文件系统容量信息。",
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "标签列表。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "标签键值对。",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "标签键。",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "标签类型。取值说明如下：System：系统标签,Custom：自定义标签。",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "标签值。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "标签键。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Type
					"type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "标签类型。取值说明如下：System：系统标签,Custom：自定义标签。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "标签值。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "标签列表。\n 特别提示: 在使用 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "文件系统更新时间。",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "文件系统更新时间。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ZoneId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "可用区 ID。",
		//	  "type": "string"
		//	}
		"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "可用区 ID。",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ZoneName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "可用区名称。",
		//	  "type": "string"
		//	}
		"zone_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "可用区名称。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "文件系统是一种通过目录树结构管理文件的存储系统，分为本地文件系统和远程文件系统，此处特指远程文件系统，支持多个计算节点并发访问，共享数据集。",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::EFS::FileSystem").WithTerraformTypeName("volcenginecc_efs_file_system")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"access_point_limit":    "AccessPointLimit",
		"bandwidth_mode":        "BandwidthMode",
		"baseline_bandwidth":    "BaselineBandwidth",
		"baseline_iops":         "BaselineIops",
		"burst_bandwidth":       "BurstBandwidth",
		"burst_iops":            "BurstIops",
		"capacity_limit":        "CapacityLimit",
		"capacity_used":         "CapacityUsed",
		"charge_config":         "ChargeConfig",
		"charge_status":         "ChargeStatus",
		"charge_type":           "ChargeType",
		"create_time":           "CreateTime",
		"description":           "Description",
		"downgrade_unlock_time": "DowngradeUnlockTime",
		"expire_time":           "ExpireTime",
		"file_system_id":        "FileSystemId",
		"file_system_name":      "FileSystemName",
		"inode_limit":           "InodeLimit",
		"inode_used":            "InodeUsed",
		"instance_type":         "InstanceType",
		"key":                   "Key",
		"mount_point_limit":     "MountPointLimit",
		"performance":           "Performance",
		"performance_density":   "PerformanceDensity",
		"project_name":          "ProjectName",
		"protocol_types":        "ProtocolTypes",
		"provisioned_bandwidth": "ProvisionedBandwidth",
		"provisioned_iops":      "ProvisionedIops",
		"reclaim_time":          "ReclaimTime",
		"status":                "Status",
		"stop_time":             "StopTime",
		"storage":               "Storage",
		"tags":                  "Tags",
		"type":                  "Type",
		"update_time":           "UpdateTime",
		"value":                 "Value",
		"zone_id":               "ZoneId",
		"zone_name":             "ZoneName",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/ChargeType",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/AccessPointLimit",
		"/properties/ChargeConfig",
		"/properties/CreateTime",
		"/properties/DowngradeUnlockTime",
		"/properties/FileSystemId",
		"/properties/MountPointLimit",
		"/properties/Performance/BaselineBandwidth",
		"/properties/Performance/BaselineIops",
		"/properties/Performance/BurstIops",
		"/properties/Performance/ProvisionedIops",
		"/properties/ProtocolTypes",
		"/properties/Status",
		"/properties/Storage",
		"/properties/UpdateTime",
		"/properties/ZoneName",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ChargeType",
		"/properties/InstanceType",
		"/properties/PerformanceDensity",
		"/properties/ProjectName",
		"/properties/ZoneId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
