// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package kms

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_kms_secret", secretResource)
}

// secretResource returns the Terraform volcenginecc_kms_secret resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::KMS::Secret resource.
func secretResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AutomaticRotation
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether to enable automatic rotation. Applies only to credentials of type IAM|RDS|Redis|ECS",
		//	  "type": "boolean"
		//	}
		"automatic_rotation": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether to enable automatic rotation. Applies only to credentials of type IAM|RDS|Redis|ECS",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
				boolplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// AutomaticRotation is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential creation time",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"created_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Credential creation time",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential description, length: 0 ~ 8192 characters",
		//	  "maxLength": 8192,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential description, length: 0 ~ 8192 characters",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(8192),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: EncryptionKey
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "KMS key TRN for encrypting credential value. If not specified, the default key of Credential Manager is used",
		//	  "type": "string"
		//	}
		"encryption_key": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "KMS key TRN for encrypting credential value. If not specified, the default key of Credential Manager is used",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ExtendedConfig
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential extension configuration, used to specify properties for non-Generic credentials",
		//	  "type": "string"
		//	}
		"extended_config": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential extension configuration, used to specify properties for non-Generic credentials",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: LastRotationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential last rotation time",
		//	  "type": "string"
		//	}
		"last_rotation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential last rotation time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Managed
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Is managed credential",
		//	  "type": "boolean"
		//	}
		"managed": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Is managed credential",
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: OwningService
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Managed Cloud Service",
		//	  "type": "string"
		//	}
		"owning_service": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Managed Cloud Service",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential project name. Default value: default",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential project name. Default value: default",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RotationInterval
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Automatic rotation interval. Range: 1 ~ 365 days. Format: integer[unit], where integer is the duration and unit is the time unit. Unit value: d (days). For example: 7d means a 7-day interval",
		//	  "type": "string"
		//	}
		"rotation_interval": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Automatic rotation interval. Range: 1 ~ 365 days. Format: integer[unit], where integer is the duration and unit is the time unit. Unit value: d (days). For example: 7d means a 7-day interval",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// RotationInterval is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: RotationIntervalRead
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Automatic rotation interval, unit: seconds",
		//	  "type": "integer"
		//	}
		"rotation_interval_read": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Automatic rotation interval, unit: seconds",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RotationState
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Rotation status: Enable: automatic rotation enabled, Disable: automatic rotation disabled, Rotating: automatic rotation in progress, None: automatic rotation not supported",
		//	  "type": "string"
		//	}
		"rotation_state": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Rotation status: Enable: automatic rotation enabled, Disable: automatic rotation disabled, Rotating: automatic rotation in progress, None: automatic rotation not supported",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ScheduleDeleteTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential Scheduled Deletion Time",
		//	  "type": "string"
		//	}
		"schedule_delete_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential Scheduled Deletion Time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ScheduleRotationTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential next rotation time",
		//	  "type": "string"
		//	}
		"schedule_rotation_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential next rotation time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecretID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential unique identifier, UUID format",
		//	  "type": "string"
		//	}
		"secret_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential unique identifier, UUID format",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecretName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential name. Valid characters: [a-zA-Z0-9/_+=.@-]",
		//	  "type": "string"
		//	}
		"secret_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential name. Valid characters: [a-zA-Z0-9/_+=.@-]",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecretState
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential status. Enable: enabled, Disable: disabled, PendingDelete: scheduled for deletion",
		//	  "type": "string"
		//	}
		"secret_state": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential status. Enable: enabled, Disable: disabled, PendingDelete: scheduled for deletion",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecretType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential type. Currently supports Generic|IAM|RDS|Redis|ECS|PGSQL|SQLServer",
		//	  "type": "string"
		//	}
		"secret_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential type. Currently supports Generic|IAM|RDS|Redis|ECS|PGSQL|SQLServer",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SecretValue
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential value. When SecretType is Generic, users can customize it. It is recommended to use JSON key-value pairs",
		//	  "type": "string"
		//	}
		"secret_value": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential value. When SecretType is Generic, users can customize it. It is recommended to use JSON key-value pairs",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
			// SecretValue is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: Trn
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential resource name. Format: trn:kms:${Region}:${AccountID}:secrets/${secret}",
		//	  "type": "string"
		//	}
		"trn": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential resource name. Format: trn:kms:${Region}:${AccountID}:secrets/${secret}",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential tenant ID",
		//	  "type": "string"
		//	}
		"uid": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Credential tenant ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Credential update date",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"updated_time": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Credential update date",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VersionName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Version alias. Valid characters: [a-zA-Z0-9/_+=.@-]",
		//	  "type": "string"
		//	}
		"version_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Version alias. Valid characters: [a-zA-Z0-9/_+=.@-]",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
			// VersionName is a write-only property.
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Credential Manager is a credential management product based on the key management system. It is used to store sensitive credential information required by user business applications, such as AK/SK, account passwords, access keys, database passwords, and certificates. The product provides secure storage, access control, automatic rotation, and auditing capabilities. User business applications can securely and dynamically obtain credential information by integrating the KMS SDK or using the KMS OpenAPI, effectively preventing risks such as information leakage or unintended modification caused by storing sensitive information in plaintext",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::KMS::Secret").WithTerraformTypeName("volcenginecc_kms_secret")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"automatic_rotation":     "AutomaticRotation",
		"created_time":           "CreatedTime",
		"description":            "Description",
		"encryption_key":         "EncryptionKey",
		"extended_config":        "ExtendedConfig",
		"last_rotation_time":     "LastRotationTime",
		"managed":                "Managed",
		"owning_service":         "OwningService",
		"project_name":           "ProjectName",
		"rotation_interval":      "RotationInterval",
		"rotation_interval_read": "RotationIntervalRead",
		"rotation_state":         "RotationState",
		"schedule_delete_time":   "ScheduleDeleteTime",
		"schedule_rotation_time": "ScheduleRotationTime",
		"secret_id":              "SecretID",
		"secret_name":            "SecretName",
		"secret_state":           "SecretState",
		"secret_type":            "SecretType",
		"secret_value":           "SecretValue",
		"trn":                    "Trn",
		"uid":                    "UID",
		"updated_time":           "UpdatedTime",
		"version_name":           "VersionName",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/SecretValue",
		"/properties/VersionName",
		"/properties/RotationInterval",
		"/properties/AutomaticRotation",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/RotationIntervalRead",
		"/properties/CreatedTime",
		"/properties/SecretID",
		"/properties/LastRotationTime",
		"/properties/Managed",
		"/properties/UpdatedTime",
		"/properties/OwningService",
		"/properties/RotationState",
		"/properties/ScheduleDeleteTime",
		"/properties/ScheduleRotationTime",
		"/properties/Trn",
		"/properties/UID",
		"/properties/SecretState",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/EncryptionKey",
		"/properties/ExtendedConfig",
		"/properties/ProjectName",
		"/properties/RotationInterval",
		"/properties/SecretName",
		"/properties/SecretType",
		"/properties/SecretValue",
		"/properties/VersionName",
		"/properties/AutomaticRotation",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
