// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package tls

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_tls_alarm", alarmResource)
}

// alarmResource returns the Terraform volcenginecc_tls_alarm resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::TLS::Alarm resource.
func alarmResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AlarmId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert policy ID.",
		//	  "type": "string"
		//	}
		"alarm_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert policy ID.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: AlarmName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert policy name",
		//	  "type": "string"
		//	}
		"alarm_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert policy name",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: AlarmNotifyGroups
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of notification groups corresponding to the alert.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Notification list for the alert",
		//	    "properties": {
		//	      "AlarmNotifyGroupId": {
		//	        "description": "Alert notification group ID.",
		//	        "type": "string"
		//	      },
		//	      "AlarmNotifyGroupName": {
		//	        "description": "Alert notification group name.",
		//	        "type": "string"
		//	      },
		//	      "CreateTime": {
		//	        "description": "Alert notification group creation time.",
		//	        "type": "string"
		//	      },
		//	      "IamProjectName": {
		//	        "description": "IAM project to which the alert group belongs.",
		//	        "type": "string"
		//	      },
		//	      "ModifyTime": {
		//	        "description": "Time when the alert notification group was modified.",
		//	        "type": "string"
		//	      },
		//	      "NoticeRules": {
		//	        "description": "Notification group rule",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "description": "Configuration related to set operations on alert query analysis results.",
		//	          "properties": {
		//	            "HasEndNode": {
		//	              "description": "Whether a subsequent end node exists.",
		//	              "type": "boolean"
		//	            },
		//	            "HasNext": {
		//	              "description": "Whether to continue to the next level of condition evaluation",
		//	              "type": "boolean"
		//	            },
		//	            "ReceiverInfos": {
		//	              "description": "Notification group rule",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "description": "Configuration related to set operations on alert query analysis results.",
		//	                "properties": {
		//	                  "AlarmContentTemplateId": {
		//	                    "description": "Alert content template ID.",
		//	                    "type": "string"
		//	                  },
		//	                  "AlarmWebhookAtGroups": {
		//	                    "description": "Name of the user group to be notified when sending notifications to 飞书, DingTalk, or WeCom via Webhook integration configuration.",
		//	                    "insertionOrder": false,
		//	                    "items": {
		//	                      "type": "string"
		//	                    },
		//	                    "type": "array",
		//	                    "uniqueItems": true
		//	                  },
		//	                  "AlarmWebhookAtUsers": {
		//	                    "description": "Username to notify when sending notifications to Feishu, DingTalk, or WeCom via Webhook integration configuration.",
		//	                    "insertionOrder": false,
		//	                    "items": {
		//	                      "type": "string"
		//	                    },
		//	                    "type": "array",
		//	                    "uniqueItems": true
		//	                  },
		//	                  "AlarmWebhookIntegrationId": {
		//	                    "description": "ID of the alert Webhook integration configuration. When you configure parameters starting with AlarmWebhook, it means you choose to manage the Webhook address using the Webhook integration configuration. In this case, leave parameters starting with GeneralWebhook empty; no configuration is required.",
		//	                    "type": "string"
		//	                  },
		//	                  "AlarmWebhookIntegrationName": {
		//	                    "description": "Name of the alert Webhook integration configuration. When parameters starting with AlarmWebhook are configured, it means you choose to manage Webhook addresses using the Webhook integration configuration. In this case, leave parameters starting with GeneralWebhook empty; no configuration is required.",
		//	                    "type": "string"
		//	                  },
		//	                  "AlarmWebhookIsAtAll": {
		//	                    "description": "Whether to notify all users when sending notifications to Feishu, DingTalk, or WeCom via Webhook integration configuration. true: notify all users. false: do not notify all users.",
		//	                    "type": "boolean"
		//	                  },
		//	                  "EndTime": {
		//	                    "description": "End time for receiving alert notifications. 24-hour format, HH:mm:ss, range: 00:00:00–23:59:59. StartTime cannot be later than EndTime",
		//	                    "type": "string"
		//	                  },
		//	                  "GeneralWebhookBody": {
		//	                    "description": "Custom WebHook request body. It is recommended to set the request body content according to the callback interface format requirements of the corresponding service.",
		//	                    "type": "string"
		//	                  },
		//	                  "GeneralWebhookHeaders": {
		//	                    "description": "Custom interface callback request header.",
		//	                    "insertionOrder": false,
		//	                    "items": {
		//	                      "description": "Custom interface callback request header.",
		//	                      "properties": {
		//	                        "Key": {
		//	                          "description": "Key of the custom request header.",
		//	                          "type": "string"
		//	                        },
		//	                        "Value": {
		//	                          "description": "Value of the custom request header.",
		//	                          "type": "string"
		//	                        }
		//	                      },
		//	                      "type": "object"
		//	                    },
		//	                    "type": "array",
		//	                    "uniqueItems": true
		//	                  },
		//	                  "GeneralWebhookMethod": {
		//	                    "description": "Custom interface callback method. Only POST or PUT is supported.",
		//	                    "type": "string"
		//	                  },
		//	                  "GeneralWebhookUrl": {
		//	                    "description": "Custom callback URL for the interface",
		//	                    "type": "string"
		//	                  },
		//	                  "ReceiverChannels": {
		//	                    "description": "Notification receiving channels. You can set one or more channels. Options: Email: Email. Sms: SMS. Phone: Phone call. GeneralWebhook: Custom Webhook address. 飞书: 飞书. DingTalk: DingTalk. WeCom: WeCom.",
		//	                    "insertionOrder": false,
		//	                    "items": {
		//	                      "type": "string"
		//	                    },
		//	                    "type": "array",
		//	                    "uniqueItems": true
		//	                  },
		//	                  "ReceiverNames": {
		//	                    "description": "IAM user or user group name",
		//	                    "insertionOrder": false,
		//	                    "items": {
		//	                      "type": "string"
		//	                    },
		//	                    "type": "array",
		//	                    "uniqueItems": true
		//	                  },
		//	                  "ReceiverType": {
		//	                    "description": "Recipient type. Options: User: IAM user. UserGroup: IAM user group.",
		//	                    "type": "string"
		//	                  },
		//	                  "StartTime": {
		//	                    "description": "Start time for receiving alert notifications. 24-hour format, HH:mm:ss, range: 00:00:00–23:59:59. StartTime cannot be later than EndTime.",
		//	                    "type": "string"
		//	                  }
		//	                },
		//	                "type": "object"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "RuleNode": {
		//	              "description": "Rule node, in JSON format.",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "NotifyType": {
		//	        "description": "Type of alert notification. Optional values, select one or more: Trigger - when an alert is triggered. Recovery - when an alert is recovered.",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "Receivers": {
		//	        "description": "List of IAM users who receive alerts.",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "description": "Configuration related to set operations on alert query analysis results.",
		//	          "properties": {
		//	            "AlarmContentTemplateId": {
		//	              "description": "Alert content template ID.",
		//	              "type": "string"
		//	            },
		//	            "AlarmWebhookAtGroups": {
		//	              "description": "Name of the user group to be notified when sending notifications to 飞书, DingTalk, or WeCom via Webhook integration configuration.",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "type": "string"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "AlarmWebhookAtUsers": {
		//	              "description": "Username to notify when sending notifications to Feishu, DingTalk, or WeCom via Webhook integration configuration.",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "type": "string"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "AlarmWebhookIntegrationId": {
		//	              "description": "ID of the alert Webhook integration configuration. When you configure parameters starting with AlarmWebhook, it means you choose to manage the Webhook address using the Webhook integration configuration. In this case, leave parameters starting with GeneralWebhook empty; no configuration is required.",
		//	              "type": "string"
		//	            },
		//	            "AlarmWebhookIntegrationName": {
		//	              "description": "Name of the alert Webhook integration configuration. When parameters starting with AlarmWebhook are configured, it means you choose to manage Webhook addresses using the Webhook integration configuration. In this case, leave parameters starting with GeneralWebhook empty; no configuration is required.",
		//	              "type": "string"
		//	            },
		//	            "AlarmWebhookIsAtAll": {
		//	              "description": "Whether to notify all users when sending notifications to Feishu, DingTalk, or WeCom via Webhook integration configuration. true: notify all users. false: do not notify all users.",
		//	              "type": "boolean"
		//	            },
		//	            "EndTime": {
		//	              "description": "End time for receiving alert notifications. 24-hour format, HH:mm:ss, range: 00:00:00–23:59:59. StartTime cannot be later than EndTime",
		//	              "type": "string"
		//	            },
		//	            "GeneralWebhookBody": {
		//	              "description": "Custom WebHook request body. It is recommended to set the request body content according to the callback interface format requirements of the corresponding service.",
		//	              "type": "string"
		//	            },
		//	            "GeneralWebhookHeaders": {
		//	              "description": "Custom interface callback request header.",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "description": "Custom interface callback request header.",
		//	                "properties": {
		//	                  "Key": {
		//	                    "description": "Key of the custom request header.",
		//	                    "type": "string"
		//	                  },
		//	                  "Value": {
		//	                    "description": "Value of the custom request header.",
		//	                    "type": "string"
		//	                  }
		//	                },
		//	                "type": "object"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "GeneralWebhookMethod": {
		//	              "description": "Custom interface callback method. Only POST or PUT is supported.",
		//	              "type": "string"
		//	            },
		//	            "GeneralWebhookUrl": {
		//	              "description": "Custom callback URL for the interface",
		//	              "type": "string"
		//	            },
		//	            "ReceiverChannels": {
		//	              "description": "Notification receiving channels. You can set one or more channels. Options: Email: Email. Sms: SMS. Phone: Phone call. GeneralWebhook: Custom Webhook address. 飞书: 飞书. DingTalk: DingTalk. WeCom: WeCom.",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "type": "string"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "ReceiverNames": {
		//	              "description": "IAM user or user group name",
		//	              "insertionOrder": false,
		//	              "items": {
		//	                "type": "string"
		//	              },
		//	              "type": "array",
		//	              "uniqueItems": true
		//	            },
		//	            "ReceiverType": {
		//	              "description": "Recipient type. Options: User: IAM user. UserGroup: IAM user group.",
		//	              "type": "string"
		//	            },
		//	            "StartTime": {
		//	              "description": "Start time for receiving alert notifications. 24-hour format, HH:mm:ss, range: 00:00:00–23:59:59. StartTime cannot be later than EndTime.",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": false
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"alarm_notify_groups": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: AlarmNotifyGroupId
					"alarm_notify_group_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Alert notification group ID.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: AlarmNotifyGroupName
					// Property: CreateTime
					// Property: IamProjectName
					// Property: ModifyTime
					// Property: NoticeRules
					// Property: NotifyType
					// Property: Receivers
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "List of notification groups corresponding to the alert.\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: AlarmPeriod
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert notification sending interval. When the alert is triggered continuously and reaches the specified TriggerPeriod limit, the log service sends alert notifications at the specified interval. Value range: 10–1440, unit: minutes. This parameter sets the sending interval for alert notifications across all channels. AlarmPeriod and AlarmPeriodDetail cannot both be empty. If both are specified, AlarmPeriodDetail takes precedence.",
		//	  "type": "integer"
		//	}
		"alarm_period": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Alert notification sending interval. When the alert is triggered continuously and reaches the specified TriggerPeriod limit, the log service sends alert notifications at the specified interval. Value range: 10–1440, unit: minutes. This parameter sets the sending interval for alert notifications across all channels. AlarmPeriod and AlarmPeriodDetail cannot both be empty. If both are specified, AlarmPeriodDetail takes precedence.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: AlarmPeriodDetail
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert notification sending interval. When the alert is triggered continuously and reaches the specified TriggerPeriod, the logging service sends alert notifications according to the specified interval. Value range: 10–1440, in minutes. This parameter is used to set the sending interval for each channel. AlarmPeriod and AlarmPeriodDetail cannot both be empty. If both are specified, AlarmPeriodDetail takes precedence",
		//	  "properties": {
		//	    "Email": {
		//	      "description": "Email alert interval, in minutes. Value range: 1–1440",
		//	      "type": "integer"
		//	    },
		//	    "GeneralWebhook": {
		//	      "description": "Custom Webhook alert interval, in minutes. Value range: 1–1440.",
		//	      "type": "integer"
		//	    },
		//	    "Phone": {
		//	      "description": "Phone alert cycle, in minutes. Value range: 10–1440.",
		//	      "type": "integer"
		//	    },
		//	    "SMS": {
		//	      "description": "SMS alert interval, in minutes. Value range: 10–1440",
		//	      "type": "integer"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"alarm_period_detail": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: Email
				"email": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Email alert interval, in minutes. Value range: 1–1440",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: GeneralWebhook
				"general_webhook": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Custom Webhook alert interval, in minutes. Value range: 1–1440.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: Phone
				"phone": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Phone alert cycle, in minutes. Value range: 10–1440.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: SMS
				"sms": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "SMS alert interval, in minutes. Value range: 10–1440",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Alert notification sending interval. When the alert is triggered continuously and reaches the specified TriggerPeriod, the logging service sends alert notifications according to the specified interval. Value range: 10–1440, in minutes. This parameter is used to set the sending interval for each channel. AlarmPeriod and AlarmPeriodDetail cannot both be empty. If both are specified, AlarmPeriodDetail takes precedence",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Object{ /*START PLAN MODIFIERS*/
				objectplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Condition
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert trigger conditions. Alert policies support referencing query analysis results using the $N.keyname expression. If you configure the TriggerConditions field, the Condition and Severity fields will be ignored. If you do not configure the TriggerConditions field, both Condition and Severity fields are required.",
		//	  "type": "string"
		//	}
		"condition": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert trigger conditions. Alert policies support referencing query analysis results using the $N.keyname expression. If you configure the TriggerConditions field, the Condition and Severity fields will be ignored. If you do not configure the TriggerConditions field, both Condition and Severity fields are required.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert policy creation time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert policy creation time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: JoinConfigurations
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Configuration for set operations on alert query analysis results. Log Service treats each query analysis result as a set and determines whether to trigger an alert based on the set result. When multiple execution statements (QueryRequest) are configured, multi-set association monitoring is supported. Supported set operations include Cartesian product, left join, and right join.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Configuration related to set operations on alert query analysis results.",
		//	    "properties": {
		//	      "Condition": {
		//	        "description": "Expression used for left join or right join.",
		//	        "type": "string"
		//	      },
		//	      "SetOperationType": {
		//	        "description": "Set operation type. Optional values: CrossJoin: Cartesian product. LeftJoin: Left join. RightJoin: Right join. InnerJoin: Inner join. FullJoin: Full join.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"join_configurations": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Condition
					"condition": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Expression used for left join or right join.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: SetOperationType
					"set_operation_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Set operation type. Optional values: CrossJoin: Cartesian product. LeftJoin: Left join. RightJoin: Right join. InnerJoin: Inner join. FullJoin: Full join.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Configuration for set operations on alert query analysis results. Log Service treats each query analysis result as a set and determines whether to trigger an alert based on the set result. When multiple execution statements (QueryRequest) are configured, multi-set association monitoring is supported. Supported set operations include Cartesian product, left join, and right join.\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ModifyTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last modified time of the alert policy.",
		//	  "type": "string"
		//	}
		"modify_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Last modified time of the alert policy.",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the log project where the monitored log topic resides",
		//	  "type": "string"
		//	}
		"project_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the log project where the monitored log topic resides",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: QueryRequests
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Monitoring task execution statement.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Monitoring task execution statement.",
		//	    "properties": {
		//	      "EndTimeOffset": {
		//	        "description": "Query end time, relative to the current time, in minutes. Value must be a non-positive integer and greater than StartTimeOffset. Maximum: 0, minimum: -1440",
		//	        "type": "integer"
		//	      },
		//	      "EndTimeOffsetUnit": {
		//	        "description": "Unit for the end time range of the query. Default is minutes. Supports second/minute/hour (Second, Minute, Hour).",
		//	        "type": "string"
		//	      },
		//	      "Number": {
		//	        "description": "Alert object sequence number, starting from 1 and incrementing by 1",
		//	        "type": "integer"
		//	      },
		//	      "Query": {
		//	        "description": "Query analysis statement, with a maximum supported length of 1024 characters.",
		//	        "type": "string"
		//	      },
		//	      "StartTimeOffset": {
		//	        "description": "Query start time, relative to the current time, in minutes. Value must be a non-positive integer. Maximum: 0, minimum: -1440",
		//	        "type": "integer"
		//	      },
		//	      "StartTimeOffsetUnit": {
		//	        "description": "Unit for the query start time range. The default is minutes. Supports seconds/minutes/hours (Second, Minute, Hour).",
		//	        "type": "string"
		//	      },
		//	      "TimeSpanType": {
		//	        "description": "Whether to use on-the-hour time for the query. If left blank, defaults to Relative.",
		//	        "type": "string"
		//	      },
		//	      "TopicId": {
		//	        "description": "Log topic ID monitored by the alert policy.",
		//	        "type": "string"
		//	      },
		//	      "TopicName": {
		//	        "description": "Name of the log topic monitored by the alert policy.",
		//	        "type": "string"
		//	      },
		//	      "TruncatedTime": {
		//	        "description": "Round time values, i.e., round to the nearest minute or hour (Second, Minute, Hour).",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"query_requests": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: EndTimeOffset
					"end_time_offset": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Query end time, relative to the current time, in minutes. Value must be a non-positive integer and greater than StartTimeOffset. Maximum: 0, minimum: -1440",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: EndTimeOffsetUnit
					"end_time_offset_unit": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Unit for the end time range of the query. Default is minutes. Supports second/minute/hour (Second, Minute, Hour).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Number
					// Property: Query
					"query": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Query analysis statement, with a maximum supported length of 1024 characters.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: StartTimeOffset
					"start_time_offset": schema.Int64Attribute{ /*START ATTRIBUTE*/
						Description: "Query start time, relative to the current time, in minutes. Value must be a non-positive integer. Maximum: 0, minimum: -1440",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
							int64planmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: StartTimeOffsetUnit
					"start_time_offset_unit": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Unit for the query start time range. The default is minutes. Supports seconds/minutes/hours (Second, Minute, Hour).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: TimeSpanType
					"time_span_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Whether to use on-the-hour time for the query. If left blank, defaults to Relative.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: TopicId
					"topic_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Log topic ID monitored by the alert policy.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: TopicName
					"topic_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Name of the log topic monitored by the alert policy.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: TruncatedTime
					"truncated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Round time values, i.e., round to the nearest minute or hour (Second, Minute, Hour).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Monitoring task execution statement.\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: RequestCycle
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Monitoring task execution statement.",
		//	  "properties": {
		//	    "CronTab": {
		//	      "description": "Cron expression. Log Service uses a Cron expression to specify the scheduled execution of alert tasks. The minimum granularity is one minute, using a 24-hour format. For example, 0 18 * * * means the alert task runs once daily at 18:00.",
		//	      "type": "string"
		//	    },
		//	    "CronTimeZone": {
		//	      "description": "Time zone in which the Cron expression takes effect.",
		//	      "type": "string"
		//	    },
		//	    "Time": {
		//	      "description": "Scheduling cycle or the specific time point for periodic execution (minutes from 00:00). Value range: 1–1440, in minutes.",
		//	      "type": "integer"
		//	    },
		//	    "Type": {
		//	      "description": "Scheduling interval type. Options: Period: schedule at regular intervals. Fixed: schedule at a fixed time each day. Cron: use a Cron expression.",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"request_cycle": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: CronTab
				"cron_tab": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Cron expression. Log Service uses a Cron expression to specify the scheduled execution of alert tasks. The minimum granularity is one minute, using a 24-hour format. For example, 0 18 * * * means the alert task runs once daily at 18:00.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: CronTimeZone
				"cron_time_zone": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Time zone in which the Cron expression takes effect.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: Time
				"time": schema.Int64Attribute{ /*START ATTRIBUTE*/
					Description: "Scheduling cycle or the specific time point for periodic execution (minutes from 00:00). Value range: 1–1440, in minutes.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
						int64planmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
				// Property: Type
				"type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Scheduling interval type. Options: Period: schedule at regular intervals. Fixed: schedule at a fixed time each day. Cron: use a Cron expression.",
					Optional:    true,
					Computed:    true,
					PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
						stringplanmodifier.UseStateForUnknown(),
					}, /*END PLAN MODIFIERS*/
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Monitoring task execution statement.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: SendResolved
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enable alert policy. Default is true (enabled)",
		//	  "type": "boolean"
		//	}
		"send_resolved": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Enable alert policy. Default is true (enabled)",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Severity
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert notification level, indicating the severity of the alert. Supported values: notice, warning, or critical. Default is notice",
		//	  "type": "string"
		//	}
		"severity": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Alert notification level, indicating the severity of the alert. Supported values: notice, warning, or critical. Default is notice",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Enable alert policy. Default is true (enabled)",
		//	  "type": "boolean"
		//	}
		"status": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Enable alert policy. Default is true (enabled)",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
				boolplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TriggerConditions
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Alert trigger condition list. You can configure up to 10 alert trigger conditions. If you configure the TriggerConditions field, the Condition and Severity fields will be ignored. If you do not configure the TriggerConditions field, the Condition and Severity fields are required",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Configuration related to set operations on alert query analysis results.",
		//	    "properties": {
		//	      "Condition": {
		//	        "description": "Alert trigger condition expression.",
		//	        "type": "string"
		//	      },
		//	      "CountCondition": {
		//	        "description": "Numerical expression for scenarios with data or specific entries, implemented using __count__.",
		//	        "type": "string"
		//	      },
		//	      "NoData": {
		//	        "description": "When enabled, if the result after set operations is an empty set, a separate no-data alert is triggered.",
		//	        "type": "boolean"
		//	      },
		//	      "Severity": {
		//	        "description": "Alert notification level, indicating the severity of the alert. Supports notice, warning, or critical, with severity increasing in that order. The default is notice.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"trigger_conditions": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Condition
					"condition": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Alert trigger condition expression.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: CountCondition
					"count_condition": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Numerical expression for scenarios with data or specific entries, implemented using __count__.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: NoData
					"no_data": schema.BoolAttribute{ /*START ATTRIBUTE*/
						Description: "When enabled, if the result after set operations is an empty set, a separate no-data alert is triggered.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{ /*START PLAN MODIFIERS*/
							boolplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Severity
					"severity": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Alert notification level, indicating the severity of the alert. Supports notice, warning, or critical, with severity increasing in that order. The default is notice.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Alert trigger condition list. You can configure up to 10 alert trigger conditions. If you configure the TriggerConditions field, the Condition and Severity fields will be ignored. If you do not configure the TriggerConditions field, the Condition and Severity fields are required\n Important Note: When using SetNestedAttribute, you must fully define all attributes of its nested structure. Incomplete definitions may cause Terraform to detect unexpected differences during plan comparison, triggering unnecessary resource updates and affecting resource stability and predictability.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: TriggerPeriod
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Duration period. An alert is triggered after the trigger condition is continuously met for TriggerPeriod cycles. Minimum value: 1, maximum value: 10, default is 1.",
		//	  "type": "integer"
		//	}
		"trigger_period": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Duration period. An alert is triggered after the trigger condition is continuously met for TriggerPeriod cycles. Minimum value: 1, maximum value: 10, default is 1.",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: UserDefineMsg
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Customize alert notification content. You can insert content variables and functions. For details, see the documentation for content variables and content functions. To display this content in the actual alert notification, reference it in the content template using the NotifyMsg variable.",
		//	  "type": "string"
		//	}
		"user_define_msg": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Customize alert notification content. You can insert content variables and functions. For details, see the documentation for content variables and content functions. To display this content in the actual alert notification, reference it in the content template using the NotifyMsg variable.",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "Alert policy. The logging service periodically analyzes data and sends alerts that meet the trigger conditions to the specified notification objects",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::TLS::Alarm").WithTerraformTypeName("volcenginecc_tls_alarm")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"alarm_id":                "AlarmId",
		"alarm_name":              "AlarmName",
		"alarm_notify_group_id":   "AlarmNotifyGroupId",
		"alarm_notify_group_name": "AlarmNotifyGroupName",
		"alarm_notify_groups":     "AlarmNotifyGroups",
		"alarm_period":            "AlarmPeriod",
		"alarm_period_detail":     "AlarmPeriodDetail",
		"condition":               "Condition",
		"count_condition":         "CountCondition",
		"create_time":             "CreateTime",
		"cron_tab":                "CronTab",
		"cron_time_zone":          "CronTimeZone",
		"email":                   "Email",
		"end_time_offset":         "EndTimeOffset",
		"end_time_offset_unit":    "EndTimeOffsetUnit",
		"general_webhook":         "GeneralWebhook",
		"iam_project_name":        "IamProjectName",
		"join_configurations":     "JoinConfigurations",
		"modify_time":             "ModifyTime",
		"no_data":                 "NoData",
		"notice_rules":            "NoticeRules",
		"notify_type":             "NotifyType",
		"number":                  "Number",
		"phone":                   "Phone",
		"project_id":              "ProjectId",
		"query":                   "Query",
		"query_requests":          "QueryRequests",
		"receivers":               "Receivers",
		"request_cycle":           "RequestCycle",
		"send_resolved":           "SendResolved",
		"set_operation_type":      "SetOperationType",
		"severity":                "Severity",
		"sms":                     "SMS",
		"start_time_offset":       "StartTimeOffset",
		"start_time_offset_unit":  "StartTimeOffsetUnit",
		"status":                  "Status",
		"time":                    "Time",
		"time_span_type":          "TimeSpanType",
		"topic_id":                "TopicId",
		"topic_name":              "TopicName",
		"trigger_conditions":      "TriggerConditions",
		"trigger_period":          "TriggerPeriod",
		"truncated_time":          "TruncatedTime",
		"type":                    "Type",
		"user_define_msg":         "UserDefineMsg",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/AlarmId",
		"/properties/CreateTime",
		"/properties/ModifyTime",
		"/properties/AlarmNotifyGroups/*/Receivers",
		"/properties/AlarmNotifyGroups/*/CreateTime",
		"/properties/AlarmNotifyGroups/*/ModifyTime",
		"/properties/AlarmNotifyGroups/*/NotifyType",
		"/properties/AlarmNotifyGroups/*/NoticeRules",
		"/properties/AlarmNotifyGroups/*/IamProjectName",
		"/properties/AlarmNotifyGroups/*/AlarmNotifyGroupName",
		"/properties/QueryRequests/*/Number",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ProjectId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
