// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package storageebs_test

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/acctest"
)

func TestAccVolcengineStorageEBSVolume_basic(t *testing.T) {
	td := acctest.NewTestData(t, "Volcengine::StorageEBS::Volume", "volcenginecc_storageebs_volume", "test")

	td.ResourceTest(t, []resource.TestStep{
		{
			Config:      td.EmptyConfig(),
			ExpectError: regexp.MustCompile("Missing required argument"),
		},
	})
}
