// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package cloudidentity

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_cloudidentity_user_provisioning", userProvisioningDataSource)
}

// userProvisioningDataSource returns the Terraform volcenginecc_cloudidentity_user_provisioning data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::CloudIdentity::UserProvisioning resource.
func userProvisioningDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation Time",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DeletionStrategy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Deletion Policy",
		//	  "type": "string"
		//	}
		"deletion_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Deletion Policy",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Task Description",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Task Description",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DuplicationStrategy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Username Conflict Policy",
		//	  "type": "string"
		//	}
		"duplication_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Username Conflict Policy",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DuplicationSuffix
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Suffix for IAM user name in this synchronization",
		//	  "type": "string"
		//	}
		"duplication_suffix": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Suffix for IAM user name in this synchronization",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: IdentitySourceStrategy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Identity Source Conflict Policy",
		//	  "type": "string"
		//	}
		"identity_source_strategy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Identity Source Conflict Policy",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PrincipalId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Identity ID",
		//	  "type": "string"
		//	}
		"principal_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Identity ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PrincipalName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Target Name",
		//	  "type": "string"
		//	}
		"principal_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Target Name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: PrincipalType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Identity Type",
		//	  "type": "string"
		//	}
		"principal_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Identity Type",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProvisionStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Authorization Task Status. Provisioned: authorization successful, Provisioning: authorizing, DeleteProvisioning: revoking authorization, DeleteProvisioned: authorization revoked successfully.",
		//	  "type": "string"
		//	}
		"provision_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Authorization Task Status. Provisioned: authorization successful, Provisioning: authorizing, DeleteProvisioning: revoking authorization, DeleteProvisioned: authorization revoked successfully.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TargetId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Target ID",
		//	  "type": "string"
		//	}
		"target_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Target ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update Time",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update Time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UserProvisioningId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IAM User Synchronization Task ID",
		//	  "type": "string"
		//	}
		"user_provisioning_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IAM User Synchronization Task ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::CloudIdentity::UserProvisioning",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CloudIdentity::UserProvisioning").WithTerraformTypeName("volcenginecc_cloudidentity_user_provisioning")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"created_time":             "CreatedTime",
		"deletion_strategy":        "DeletionStrategy",
		"description":              "Description",
		"duplication_strategy":     "DuplicationStrategy",
		"duplication_suffix":       "DuplicationSuffix",
		"identity_source_strategy": "IdentitySourceStrategy",
		"principal_id":             "PrincipalId",
		"principal_name":           "PrincipalName",
		"principal_type":           "PrincipalType",
		"provision_status":         "ProvisionStatus",
		"target_id":                "TargetId",
		"updated_time":             "UpdatedTime",
		"user_provisioning_id":     "UserProvisioningId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
