// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package natgateway

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_natgateway_snatentry", snatentryDataSource)
}

// snatentryDataSource returns the Terraform volcenginecc_natgateway_snatentry data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::NatGateway::Snatentry resource.
func snatentryDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: EipAddress
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address of the public IP associated with the SNAT rule. Returns the IP address for a single public IP. Returns IP addresses for multiple public IPs.",
		//	  "type": "string"
		//	}
		"eip_address": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IP address of the public IP associated with the SNAT rule. Returns the IP address for a single public IP. Returns IP addresses for multiple public IPs.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: EipId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the public IP associated with the SNAT rule. Returns the ID for a single public IP. Returns IDs for multiple public IPs.",
		//	  "type": "string"
		//	}
		"eip_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the public IP associated with the SNAT rule. Returns the ID for a single public IP. Returns IDs for multiple public IPs.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NatGatewayId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the NAT gateway associated with the SNAT rule",
		//	  "type": "string"
		//	}
		"nat_gateway_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the NAT gateway associated with the SNAT rule",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NatIpId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the transit IP for the private NAT gateway",
		//	  "type": "string"
		//	}
		"nat_ip_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the transit IP for the private NAT gateway",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SnatEntryId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the SNAT rule",
		//	  "type": "string"
		//	}
		"snat_entry_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the SNAT rule",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SnatEntryName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the SNAT rule",
		//	  "type": "string"
		//	}
		"snat_entry_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the SNAT rule",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceCidr
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Network segment corresponding to the SNAT rule",
		//	  "type": "string"
		//	}
		"source_cidr": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Network segment corresponding to the SNAT rule",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the SNAT rule. Creating: being created. Deleting: being deleted. Available: available.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the SNAT rule. Creating: being created. Deleting: being deleted. Available: available.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SubnetId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "ID of the subnet associated with the SNAT rule",
		//	  "type": "string"
		//	}
		"subnet_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "ID of the subnet associated with the SNAT rule",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::NatGateway::Snatentry",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::NatGateway::Snatentry").WithTerraformTypeName("volcenginecc_natgateway_snatentry")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"eip_address":     "EipAddress",
		"eip_id":          "EipId",
		"nat_gateway_id":  "NatGatewayId",
		"nat_ip_id":       "NatIpId",
		"snat_entry_id":   "SnatEntryId",
		"snat_entry_name": "SnatEntryName",
		"source_cidr":     "SourceCidr",
		"status":          "Status",
		"subnet_id":       "SubnetId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
