// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package rdspostgresql

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_rdspostgresql_instance", instanceDataSource)
}

// instanceDataSource returns the Terraform volcenginecc_rdspostgresql_instance data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::RDSPostgreSQL::Instance resource.
func instanceDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AllowListIds
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist ID. To bind multiple allowlists, separate allowlist IDs with commas (,). An instance can bind up to 100 allowlists.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"allow_list_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "Allowlist ID. To bind multiple allowlists, separate allowlist IDs with commas (,). An instance can bind up to 100 allowlists.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ChargeDetail
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Payment method",
		//	  "properties": {
		//	    "AutoRenew": {
		//	      "description": "Enable auto-renewal for prepaid scenarios",
		//	      "type": "boolean"
		//	    },
		//	    "ChargeEndTime": {
		//	      "description": "Billing expiration time for yearly/monthly instances",
		//	      "type": "string"
		//	    },
		//	    "ChargeStartTime": {
		//	      "description": "Instance billing start time",
		//	      "type": "string"
		//	    },
		//	    "ChargeStatus": {
		//	      "description": "Payment status. Value: - `Normal`: Normal - `Overdue`: Overdue and suspended - `Unpaid`: Unpaid",
		//	      "enum": [
		//	        "Normal",
		//	        "Overdue",
		//	        "Unpaid"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "ChargeType": {
		//	      "description": "Payment type. Value: - `PostPaid`: Postpaid - `PrePaid`: Prepaid",
		//	      "enum": [
		//	        "PostPaid",
		//	        "PrePaid"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "OverdueReclaimTime": {
		//	      "description": "Estimated release time after instance suspension due to overdue payment",
		//	      "type": "string"
		//	    },
		//	    "OverdueTime": {
		//	      "description": "Instance shutdown time due to overdue payment",
		//	      "type": "string"
		//	    },
		//	    "Period": {
		//	      "description": "Purchase duration for prepaid scenarios",
		//	      "type": "number"
		//	    },
		//	    "PeriodUnit": {
		//	      "description": "Purchase period for prepaid scenarios. Values: - `Month`: month - `Year`: year",
		//	      "enum": [
		//	        "Month",
		//	        "Year"
		//	      ],
		//	      "type": "string"
		//	    },
		//	    "TempModifyEndTime": {
		//	      "description": "Rollback time for temporary upgrade",
		//	      "type": "string"
		//	    },
		//	    "TempModifyStartTime": {
		//	      "description": "Start time of temporary scaling",
		//	      "type": "string"
		//	    }
		//	  },
		//	  "required": [
		//	    "ChargeType"
		//	  ],
		//	  "type": "object"
		//	}
		"charge_detail": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: AutoRenew
				"auto_renew": schema.BoolAttribute{ /*START ATTRIBUTE*/
					Description: "Enable auto-renewal for prepaid scenarios",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ChargeEndTime
				"charge_end_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Billing expiration time for yearly/monthly instances",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ChargeStartTime
				"charge_start_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Instance billing start time",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ChargeStatus
				"charge_status": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Payment status. Value:   - `Normal`: Normal   - `Overdue`: Overdue and suspended   - `Unpaid`: Unpaid",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: ChargeType
				"charge_type": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Payment type. Value:   - `PostPaid`: Postpaid   - `PrePaid`: Prepaid",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: OverdueReclaimTime
				"overdue_reclaim_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Estimated release time after instance suspension due to overdue payment",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: OverdueTime
				"overdue_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Instance shutdown time due to overdue payment",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: Period
				"period": schema.Float64Attribute{ /*START ATTRIBUTE*/
					Description: "Purchase duration for prepaid scenarios",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: PeriodUnit
				"period_unit": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Purchase period for prepaid scenarios. Values:   - `Month`: month   - `Year`: year",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: TempModifyEndTime
				"temp_modify_end_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Rollback time for temporary upgrade",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: TempModifyStartTime
				"temp_modify_start_time": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Start time of temporary scaling",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Payment method",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance creation time",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance creation time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DBEngineVersion
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Compatible version",
		//	  "type": "string"
		//	}
		"db_engine_version": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Compatible version",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DataSyncMode
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Synchronization mode. Value: Async (asynchronous synchronization)",
		//	  "type": "string"
		//	}
		"data_sync_mode": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Synchronization mode. Value: Async (asynchronous synchronization)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Endpoints
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance connection information",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Instance connection information",
		//	    "properties": {
		//	      "Address": {
		//	        "description": "Address list.",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "description": "Address list",
		//	          "properties": {
		//	            "CrossRegionDomain": {
		//	              "description": "Private network address accessible across regions",
		//	              "type": "string"
		//	            },
		//	            "DNSVisibility": {
		//	              "description": "Enable public network resolution. Values: - false: default, private network resolution - true: private and public network resolution",
		//	              "type": "boolean"
		//	            },
		//	            "Domain": {
		//	              "description": "Connection domain name",
		//	              "type": "string"
		//	            },
		//	            "DomainVisibilitySetting": {
		//	              "description": "Private network address type. Values: LocalDomain: local region domain name CrossRegionDomain: cross-region accessible domain name",
		//	              "type": "string"
		//	            },
		//	            "EipId": {
		//	              "description": "EIP ID, valid only for Public addresses",
		//	              "type": "string"
		//	            },
		//	            "IPAddress": {
		//	              "description": "IP address",
		//	              "type": "string"
		//	            },
		//	            "NetworkType": {
		//	              "description": "Network address type. Value: - `Private`: Private network address - `Public`: Public network address - `Inner`: Public service zone address",
		//	              "type": "string"
		//	            },
		//	            "Port": {
		//	              "description": "Port.",
		//	              "type": "string"
		//	            },
		//	            "SubnetId": {
		//	              "description": "Subnet ID",
		//	              "type": "string"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "AutoAddNewNodes": {
		//	        "description": "When the terminal type is read-write or read-only, you can set whether new nodes join automatically. Values: - `Enable`: join automatically - `Disable`: do not join automatically (default)",
		//	        "type": "string"
		//	      },
		//	      "Description": {
		//	        "description": "Address description.",
		//	        "type": "string"
		//	      },
		//	      "EnableReadOnly": {
		//	        "description": "Enable global read-only mode. - `Enable`: enabled - `Disable`: not enabled",
		//	        "type": "string"
		//	      },
		//	      "EnableReadWriteSplitting": {
		//	        "description": "Enable read-write separation. Values: - `Enable`: enabled - `Disable`: not enabled",
		//	        "type": "string"
		//	      },
		//	      "EndpointId": {
		//	        "description": "Instance connection terminal ID",
		//	        "type": "string"
		//	      },
		//	      "EndpointName": {
		//	        "description": "Instance connection terminal name",
		//	        "type": "string"
		//	      },
		//	      "EndpointType": {
		//	        "description": "Endpoint type: - `Cluster`: Default endpoint (created by default) - `Custom`: Custom endpoint",
		//	        "type": "string"
		//	      },
		//	      "ReadOnlyNodeDistributionType": {
		//	        "description": "Read-only weight allocation mode. Options: - `Default`: Standard weight allocation (default). - `Custom`: Custom weight allocation",
		//	        "type": "string"
		//	      },
		//	      "ReadOnlyNodeMaxDelayTime": {
		//	        "description": "Maximum latency threshold for read-only nodes. If a read-only node's latency exceeds this value, read traffic will not be sent to that node. Unit: seconds. Range: 0~3600. Default: 30. :::tip This parameter can be set for the default endpoint when read/write splitting is enabled.:::",
		//	        "type": "number"
		//	      },
		//	      "ReadOnlyNodeWeight": {
		//	        "description": "List of nodes configured for the endpoint and their corresponding read-only weights.",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "description": "List of nodes configured for the endpoint and their corresponding read-only weights",
		//	          "properties": {
		//	            "NodeId": {
		//	              "description": "Read-only nodes require NodeId",
		//	              "type": "string"
		//	            },
		//	            "NodeType": {
		//	              "description": "Node type",
		//	              "type": "string"
		//	            },
		//	            "Weight": {
		//	              "description": "Node read weight, increases by 100, maximum value is 10000",
		//	              "type": "number"
		//	            }
		//	          },
		//	          "type": "object"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "ReadWriteMode": {
		//	        "description": "Read/write mode: - `ReadWrite`: Read/write - `ReadOnly`: Read-only",
		//	        "type": "string"
		//	      },
		//	      "ReadWriteProxyConnection": {
		//	        "description": "After read/write splitting is enabled for the terminal, set the number of proxy connections for the terminal. - The minimum value for proxy connections is 20. - The maximum value depends on the specification of the instance's primary node. Different specifications support different maximum proxy connections. For details, see [Product Specifications]",
		//	        "type": "number"
		//	      },
		//	      "WriteNodeHaltWriting": {
		//	        "description": "Whether the endpoint sends write requests to the write node (currently, only the primary node is the write node). Value: - `true`: Yes. (Default) - `false`: No",
		//	        "type": "boolean"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"endpoints": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Address
					"address": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
						NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: CrossRegionDomain
								"cross_region_domain": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Private network address accessible across regions",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: DNSVisibility
								"dns_visibility": schema.BoolAttribute{ /*START ATTRIBUTE*/
									Description: "Enable public network resolution. Values:   - false: default, private network resolution   - true: private and public network resolution",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: Domain
								"domain": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Connection domain name",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: DomainVisibilitySetting
								"domain_visibility_setting": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Private network address type. Values: LocalDomain: local region domain name CrossRegionDomain: cross-region accessible domain name",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: EipId
								"eip_id": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "EIP ID, valid only for Public addresses",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: IPAddress
								"ip_address": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "IP address",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: NetworkType
								"network_type": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Network address type. Value:   - `Private`: Private network address   - `Public`: Public network address   - `Inner`: Public service zone address",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: Port
								"port": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Port.",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: SubnetId
								"subnet_id": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Subnet ID",
									Computed:    true,
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
						}, /*END NESTED OBJECT*/
						Description: "Address list.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: AutoAddNewNodes
					"auto_add_new_nodes": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "When the terminal type is read-write or read-only, you can set whether new nodes join automatically. Values:   - `Enable`: join automatically   - `Disable`: do not join automatically (default)",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Address description.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: EnableReadOnly
					"enable_read_only": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Enable global read-only mode.   - `Enable`: enabled   - `Disable`: not enabled",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: EnableReadWriteSplitting
					"enable_read_write_splitting": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Enable read-write separation. Values:   - `Enable`: enabled   - `Disable`: not enabled",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: EndpointId
					"endpoint_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance connection terminal ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: EndpointName
					"endpoint_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance connection terminal name",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: EndpointType
					"endpoint_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Endpoint type:   - `Cluster`: Default endpoint (created by default)   - `Custom`: Custom endpoint",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ReadOnlyNodeDistributionType
					"read_only_node_distribution_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Read-only weight allocation mode. Options:   - `Default`: Standard weight allocation (default).   - `Custom`: Custom weight allocation",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ReadOnlyNodeMaxDelayTime
					"read_only_node_max_delay_time": schema.Float64Attribute{ /*START ATTRIBUTE*/
						Description: "Maximum latency threshold for read-only nodes. If a read-only node's latency exceeds this value, read traffic will not be sent to that node. Unit: seconds. Range: 0~3600. Default: 30. \n  **Note:** This parameter can be set for the default endpoint when read/write splitting is enabled.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ReadOnlyNodeWeight
					"read_only_node_weight": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
						NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
							Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
								// Property: NodeId
								"node_id": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Read-only nodes require NodeId",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: NodeType
								"node_type": schema.StringAttribute{ /*START ATTRIBUTE*/
									Description: "Node type",
									Computed:    true,
								}, /*END ATTRIBUTE*/
								// Property: Weight
								"weight": schema.Float64Attribute{ /*START ATTRIBUTE*/
									Description: "Node read weight, increases by 100, maximum value is 10000",
									Computed:    true,
								}, /*END ATTRIBUTE*/
							}, /*END SCHEMA*/
						}, /*END NESTED OBJECT*/
						Description: "List of nodes configured for the endpoint and their corresponding read-only weights.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ReadWriteMode
					"read_write_mode": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Read/write mode:   - `ReadWrite`: Read/write   - `ReadOnly`: Read-only",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ReadWriteProxyConnection
					"read_write_proxy_connection": schema.Float64Attribute{ /*START ATTRIBUTE*/
						Description: "After read/write splitting is enabled for the terminal, set the number of proxy connections for the terminal.   - The minimum value for proxy connections is 20.   - The maximum value depends on the specification of the instance's primary node. Different specifications support different maximum proxy connections. For details, see [Product Specifications]",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: WriteNodeHaltWriting
					"write_node_halt_writing": schema.BoolAttribute{ /*START ATTRIBUTE*/
						Description: "Whether the endpoint sends write requests to the write node (currently, only the primary node is the write node). Value:   - `true`: Yes. (Default)   - `false`: No",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Instance connection information",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance ID",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance name",
		//	  "type": "string"
		//	}
		"instance_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceStatus
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance status",
		//	  "type": "string"
		//	}
		"instance_status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance status",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance type. Value: HA (high availability edition)",
		//	  "type": "string"
		//	}
		"instance_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance type. Value: HA (high availability edition)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: MaintenanceWindow
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance maintenance window",
		//	  "properties": {
		//	    "DayKind": {
		//	      "description": "Granularity of the maintenance cycle. Value: Week (week)",
		//	      "type": "string"
		//	    },
		//	    "DayOfWeekMaintenanceTime": {
		//	      "description": "Detailed information about the instance's maintenance window.",
		//	      "items": {
		//	        "description": "Detailed information about the instance's maintenance window.",
		//	        "properties": {
		//	          "DayOfWeek": {
		//	            "description": "Specify maintenance days for the instance each week. Multiple selections allowed. Monday: Monday. Tuesday: Tuesday. Wednesday: Wednesday. Thursday: Thursday. Friday: Friday. Saturday: Saturday. Sunday: Sunday. Note: If not specified or left blank, all seven days are enabled by default.",
		//	            "type": "string"
		//	          },
		//	          "MaintenanceWindowStartTime": {
		//	            "description": "Start time of the maintenance window on the maintenance day. Format: HH:mmZ (UTC time). Currently, only start times between 16:00Z and 20:00Z are supported.",
		//	            "type": "string"
		//	          },
		//	          "Period": {
		//	            "description": "Duration of the maintenance window on the maintenance day. Minimum duration is 2 hours, maximum is 6 hours.",
		//	            "format": "int32",
		//	            "type": "integer"
		//	          }
		//	        },
		//	        "type": "object"
		//	      },
		//	      "type": "array"
		//	    }
		//	  },
		//	  "type": "object"
		//	}
		"maintenance_window": schema.SingleNestedAttribute{ /*START ATTRIBUTE*/
			Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
				// Property: DayKind
				"day_kind": schema.StringAttribute{ /*START ATTRIBUTE*/
					Description: "Granularity of the maintenance cycle. Value: Week (week)",
					Computed:    true,
				}, /*END ATTRIBUTE*/
				// Property: DayOfWeekMaintenanceTime
				"day_of_week_maintenance_time": schema.ListNestedAttribute{ /*START ATTRIBUTE*/
					NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
						Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
							// Property: DayOfWeek
							"day_of_week": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Specify maintenance days for the instance each week. Multiple selections allowed. Monday: Monday. Tuesday: Tuesday. Wednesday: Wednesday. Thursday: Thursday. Friday: Friday. Saturday: Saturday. Sunday: Sunday. Note: If not specified or left blank, all seven days are enabled by default.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: MaintenanceWindowStartTime
							"maintenance_window_start_time": schema.StringAttribute{ /*START ATTRIBUTE*/
								Description: "Start time of the maintenance window on the maintenance day. Format: HH:mmZ (UTC time). Currently, only start times between 16:00Z and 20:00Z are supported.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
							// Property: Period
							"period": schema.Int64Attribute{ /*START ATTRIBUTE*/
								Description: "Duration of the maintenance window on the maintenance day. Minimum duration is 2 hours, maximum is 6 hours.",
								Computed:    true,
							}, /*END ATTRIBUTE*/
						}, /*END SCHEMA*/
					}, /*END NESTED OBJECT*/
					Description: "Detailed information about the instance's maintenance window.",
					Computed:    true,
				}, /*END ATTRIBUTE*/
			}, /*END SCHEMA*/
			Description: "Instance maintenance window",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Memory
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Memory size, unit: GB",
		//	  "type": "number"
		//	}
		"memory": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Memory size, unit: GB",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodeInfo
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance specification configuration",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Instance specification configuration. There must be exactly 1 Primary node, exactly 1 Secondary node, and 0–10 Read-Only nodes",
		//	    "properties": {
		//	      "CreateTime": {
		//	        "description": "Node creation time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC time)",
		//	        "type": "string"
		//	      },
		//	      "InstanceId": {
		//	        "description": "Instance ID",
		//	        "type": "string"
		//	      },
		//	      "Memory": {
		//	        "description": "Memory size, unit: GB",
		//	        "type": "number"
		//	      },
		//	      "NodeId": {
		//	        "description": "Node ID",
		//	        "type": "string"
		//	      },
		//	      "NodeSpec": {
		//	        "description": "Node specification",
		//	        "type": "string"
		//	      },
		//	      "NodeStatus": {
		//	        "description": "Node status",
		//	        "type": "string"
		//	      },
		//	      "NodeType": {
		//	        "description": "Node type",
		//	        "type": "string"
		//	      },
		//	      "RegionId": {
		//	        "description": "Region ID",
		//	        "type": "string"
		//	      },
		//	      "UpdateTime": {
		//	        "description": "Node update time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC time)",
		//	        "type": "string"
		//	      },
		//	      "VCPU": {
		//	        "description": "CPU size. For example: 1 means 1U",
		//	        "type": "number"
		//	      },
		//	      "ZoneId": {
		//	        "description": "Availability zone of the node",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "ZoneId",
		//	      "NodeType",
		//	      "NodeSpec"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": false
		//	}
		"node_info": schema.ListNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: CreateTime
					"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node creation time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC time)",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: InstanceId
					"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Memory
					"memory": schema.Float64Attribute{ /*START ATTRIBUTE*/
						Description: "Memory size, unit: GB",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NodeId
					"node_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NodeSpec
					"node_spec": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node specification",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NodeStatus
					"node_status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node status",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NodeType
					"node_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node type",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: RegionId
					"region_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Region ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: UpdateTime
					"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Node update time. Format: yyyy-MM-ddTHH:mm:ss.sssZ (UTC time)",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: VCPU
					"vcpu": schema.Float64Attribute{ /*START ATTRIBUTE*/
						Description: "CPU size. For example: 1 means 1U",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ZoneId
					"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Availability zone of the node",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Instance specification configuration",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodeNumber
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of nodes",
		//	  "type": "number"
		//	}
		"node_number": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of nodes",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: NodeSpec
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Primary node specification",
		//	  "type": "string"
		//	}
		"node_spec": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Primary node specification",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project. Default value: default project",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project. Default value: default project",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageDataUse
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Data file space used by the primary node. Unit: Byte",
		//	  "type": "number"
		//	}
		"storage_data_use": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Data file space used by the primary node. Unit: Byte",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageLogUse
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Log file space used by the primary node. Unit: Byte",
		//	  "type": "number"
		//	}
		"storage_log_use": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Log file space used by the primary node. Unit: Byte",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageSpace
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance storage space. Value range: [20, 3000], unit: GB, increment: 10GB. Default value is 100",
		//	  "maximum": 3000,
		//	  "minimum": 20,
		//	  "type": "number"
		//	}
		"storage_space": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Instance storage space. Value range: [20, 3000], unit: GB, increment: 10GB. Default value is 100",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageTempUse
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Temporary file space used by the primary node. Unit: Byte",
		//	  "type": "number"
		//	}
		"storage_temp_use": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Temporary file space used by the primary node. Unit: Byte",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance storage type, fixed value LocalSSD (local SSD disk)",
		//	  "type": "string"
		//	}
		"storage_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance storage type, fixed value LocalSSD (local SSD disk)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageUse
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Used storage space of the instance. Unit: Byte",
		//	  "type": "number"
		//	}
		"storage_use": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Used storage space of the instance. Unit: Byte",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: StorageWALUse
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Used WAL file space of the instance's primary node. Unit: Byte",
		//	  "type": "number"
		//	}
		"storage_wal_use": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "Used WAL file space of the instance's primary node. Unit: Byte",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SubnetId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Subnet ID",
		//	  "type": "string"
		//	}
		"subnet_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Subnet ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Tag information of the cloud disk",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Resource tag",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Tag information of the cloud disk",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance update time",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance update time",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: VCPU
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "CPU size. For example: 1 means 1U",
		//	  "type": "number"
		//	}
		"vcpu": schema.Float64Attribute{ /*START ATTRIBUTE*/
			Description: "CPU size. For example: 1 means 1U",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: VpcId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Use this parameter to specify the private network for the instance",
		//	  "type": "string"
		//	}
		"vpc_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Use this parameter to specify the private network for the instance",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ZoneId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Availability zone ID",
		//	  "type": "string"
		//	}
		"zone_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Availability zone ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::RDSPostgreSQL::Instance",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::RDSPostgreSQL::Instance").WithTerraformTypeName("volcenginecc_rdspostgresql_instance")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"address":                          "Address",
		"allow_list_ids":                   "AllowListIds",
		"auto_add_new_nodes":               "AutoAddNewNodes",
		"auto_renew":                       "AutoRenew",
		"charge_detail":                    "ChargeDetail",
		"charge_end_time":                  "ChargeEndTime",
		"charge_start_time":                "ChargeStartTime",
		"charge_status":                    "ChargeStatus",
		"charge_type":                      "ChargeType",
		"create_time":                      "CreateTime",
		"cross_region_domain":              "CrossRegionDomain",
		"data_sync_mode":                   "DataSyncMode",
		"day_kind":                         "DayKind",
		"day_of_week":                      "DayOfWeek",
		"day_of_week_maintenance_time":     "DayOfWeekMaintenanceTime",
		"db_engine_version":                "DBEngineVersion",
		"description":                      "Description",
		"dns_visibility":                   "DNSVisibility",
		"domain":                           "Domain",
		"domain_visibility_setting":        "DomainVisibilitySetting",
		"eip_id":                           "EipId",
		"enable_read_only":                 "EnableReadOnly",
		"enable_read_write_splitting":      "EnableReadWriteSplitting",
		"endpoint_id":                      "EndpointId",
		"endpoint_name":                    "EndpointName",
		"endpoint_type":                    "EndpointType",
		"endpoints":                        "Endpoints",
		"instance_id":                      "InstanceId",
		"instance_name":                    "InstanceName",
		"instance_status":                  "InstanceStatus",
		"instance_type":                    "InstanceType",
		"ip_address":                       "IPAddress",
		"key":                              "Key",
		"maintenance_window":               "MaintenanceWindow",
		"maintenance_window_start_time":    "MaintenanceWindowStartTime",
		"memory":                           "Memory",
		"network_type":                     "NetworkType",
		"node_id":                          "NodeId",
		"node_info":                        "NodeInfo",
		"node_number":                      "NodeNumber",
		"node_spec":                        "NodeSpec",
		"node_status":                      "NodeStatus",
		"node_type":                        "NodeType",
		"overdue_reclaim_time":             "OverdueReclaimTime",
		"overdue_time":                     "OverdueTime",
		"period":                           "Period",
		"period_unit":                      "PeriodUnit",
		"port":                             "Port",
		"project_name":                     "ProjectName",
		"read_only_node_distribution_type": "ReadOnlyNodeDistributionType",
		"read_only_node_max_delay_time":    "ReadOnlyNodeMaxDelayTime",
		"read_only_node_weight":            "ReadOnlyNodeWeight",
		"read_write_mode":                  "ReadWriteMode",
		"read_write_proxy_connection":      "ReadWriteProxyConnection",
		"region_id":                        "RegionId",
		"storage_data_use":                 "StorageDataUse",
		"storage_log_use":                  "StorageLogUse",
		"storage_space":                    "StorageSpace",
		"storage_temp_use":                 "StorageTempUse",
		"storage_type":                     "StorageType",
		"storage_use":                      "StorageUse",
		"storage_wal_use":                  "StorageWALUse",
		"subnet_id":                        "SubnetId",
		"tags":                             "Tags",
		"temp_modify_end_time":             "TempModifyEndTime",
		"temp_modify_start_time":           "TempModifyStartTime",
		"update_time":                      "UpdateTime",
		"value":                            "Value",
		"vcpu":                             "VCPU",
		"vpc_id":                           "VpcId",
		"weight":                           "Weight",
		"write_node_halt_writing":          "WriteNodeHaltWriting",
		"zone_id":                          "ZoneId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
