// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package alb

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_alb_health_check_template", healthCheckTemplateDataSource)
}

// healthCheckTemplateDataSource returns the Terraform volcenginecc_alb_health_check_template data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::ALB::HealthCheckTemplate resource.
func healthCheckTemplateDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time of the health check template.",
		//	  "type": "string"
		//	}
		"create_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time of the health check template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the health check. Cannot start with http:// or https://. Must begin with a letter or Chinese character. May include numbers, English commas (,), periods (.), underscores (_), spaces ( ), equals signs (=), hyphens (-), Chinese commas (，), and Chinese periods (。). Length must be 1–255 characters. If not specified, defaults to an empty string.",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the health check. Cannot start with http:// or https://. Must begin with a letter or Chinese character. May include numbers, English commas (,), periods (.), underscores (_), spaces ( ), equals signs (=), hyphens (-), Chinese commas (，), and Chinese periods (。). Length must be 1–255 characters. If not specified, defaults to an empty string.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckDomain
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Domain name for the health check. This parameter is only effective when HealthCheckProtocol is set to HTTP. Requirements: Must contain at least one '.', and cannot start or end with '.'. The string can contain letters, numbers, '-', and '.' characters. '-' cannot appear at the beginning or end of the string. Length must be between 1 and 128 characters. If not specified, this parameter is empty and the load balancer uses the private IP address of each backend server for health checks.",
		//	  "type": "string"
		//	}
		"health_check_domain": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Domain name for the health check. This parameter is only effective when HealthCheckProtocol is set to HTTP. Requirements: Must contain at least one '.', and cannot start or end with '.'. The string can contain letters, numbers, '-', and '.' characters. '-' cannot appear at the beginning or end of the string. Length must be between 1 and 128 characters. If not specified, this parameter is empty and the load balancer uses the private IP address of each backend server for health checks.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckHttpCode
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "HTTP status codes indicating a successful health check. Separate multiple codes with commas. This parameter is only effective when HealthCheckProtocol is set to HTTP. Options: http_2xx (default), http_3xx (default), http_4xx, http_5xx.",
		//	  "type": "string"
		//	}
		"health_check_http_code": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "HTTP status codes indicating a successful health check. Separate multiple codes with commas. This parameter is only effective when HealthCheckProtocol is set to HTTP. Options: http_2xx (default), http_3xx (default), http_4xx, http_5xx.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckHttpVersion
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "HTTP protocol version for health checks. This parameter is effective only when HealthCheckProtocol is set to HTTP. Options: HTTP1.0 (default), HTTP1.1.",
		//	  "type": "string"
		//	}
		"health_check_http_version": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "HTTP protocol version for health checks. This parameter is effective only when HealthCheckProtocol is set to HTTP. Options: HTTP1.0 (default), HTTP1.1.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckInterval
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Interval for performing health checks. Default is 2 seconds. Range: 1–300 seconds.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"health_check_interval": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Interval for performing health checks. Default is 2 seconds. Range: 1–300 seconds.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckMethod
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Health check method. This parameter is effective only when HealthCheckProtocol is set to HTTP. Options: GETHEAD (default method)",
		//	  "type": "string"
		//	}
		"health_check_method": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Health check method. This parameter is effective only when HealthCheckProtocol is set to HTTP. Options: GETHEAD (default method)",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckPort
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Port for the health check. Options: 0: Use the backend server port for health checks. 1–65535: Use the specified port for health checks.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"health_check_port": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Port for the health check. Options: 0: Use the backend server port for health checks. 1–65535: Use the specified port for health checks.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckProtocol
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Protocol for the health check. HTTP or TCP.",
		//	  "type": "string"
		//	}
		"health_check_protocol": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Protocol for the health check. HTTP or TCP.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckTemplateId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Health check template ID.",
		//	  "type": "string"
		//	}
		"health_check_template_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Health check template ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckTemplateName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Name of the health check template. Cannot start with http:// or https://. Must start with a letter or Chinese character. Can contain numbers, periods (.), underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
		//	  "type": "string"
		//	}
		"health_check_template_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Name of the health check template. Cannot start with http:// or https://. Must start with a letter or Chinese character. Can contain numbers, periods (.), underscores (_), and hyphens (-). Length must be between 1 and 128 characters.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckTimeout
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Response timeout for the health check. Default is 2 seconds. Range: 1–60 seconds.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"health_check_timeout": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Response timeout for the health check. Default is 2 seconds. Range: 1–60 seconds.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthCheckURI
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Path for the health check. This parameter is only effective when HealthCheckProtocol is set to HTTP. Requirements: Must start with '/'. Can only contain letters, numbers, '-', '_', '/', '.', '%', '?', '#', '\u0026', '=' characters. Length must be between 1 and 128 characters. If not specified, defaults to '/'.",
		//	  "type": "string"
		//	}
		"health_check_uri": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Path for the health check. This parameter is only effective when HealthCheckProtocol is set to HTTP. Requirements: Must start with '/'. Can only contain letters, numbers, '-', '_', '/', '.', '%', '?', '#', '&', '=' characters. Length must be between 1 and 128 characters. If not specified, defaults to '/'.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: HealthyThreshold
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Health threshold for the health check. Default is 3. Range: 2–10 times.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"healthy_threshold": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Health threshold for the health check. Default is 3. Range: 2–10 times.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name to which the health check template belongs.",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name to which the health check template belongs.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "List of tags associated with the health check template.",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "description": "Tags associated with the health check template.",
		//	    "properties": {
		//	      "Key": {
		//	        "description": "Tag key for user tags. Rules: Length must be 1–128 characters. Case-sensitive. Cannot start with any case combination of sys:. Cannot start or end with a space. May include characters from any language, numbers, spaces, underscores (_), periods (.), colons (:), slashes (/), equals signs (=), plus signs (+), hyphens (-), and @. Tag keys for the same resource must be unique.",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "Tag value for the user tag. If you specify this parameter, you must first specify Tags.N.Key. Rules: Length must be between 0 and 256 characters. Case-sensitive. Cannot start or end with a space. Supports characters from all languages, numbers, spaces, underscores (_), periods (.), colons (:), slashes (/), equals signs (=), plus signs (+), minus signs (-), and @.",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag key for user tags. Rules: Length must be 1–128 characters. Case-sensitive. Cannot start with any case combination of sys:. Cannot start or end with a space. May include characters from any language, numbers, spaces, underscores (_), periods (.), colons (:), slashes (/), equals signs (=), plus signs (+), hyphens (-), and @. Tag keys for the same resource must be unique.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Tag value for the user tag. If you specify this parameter, you must first specify Tags.N.Key. Rules: Length must be between 0 and 256 characters. Case-sensitive. Cannot start or end with a space. Supports characters from all languages, numbers, spaces, underscores (_), periods (.), colons (:), slashes (/), equals signs (=), plus signs (+), minus signs (-), and @.",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "List of tags associated with the health check template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UnhealthyThreshold
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Unhealthy threshold for health checks. Default is 3; range is 2–10 times.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"unhealthy_threshold": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Unhealthy threshold for health checks. Default is 3; range is 2–10 times.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdateTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Last operation time of the health check template.",
		//	  "type": "string"
		//	}
		"update_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Last operation time of the health check template.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::ALB::HealthCheckTemplate",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::ALB::HealthCheckTemplate").WithTerraformTypeName("volcenginecc_alb_health_check_template")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"create_time":                "CreateTime",
		"description":                "Description",
		"health_check_domain":        "HealthCheckDomain",
		"health_check_http_code":     "HealthCheckHttpCode",
		"health_check_http_version":  "HealthCheckHttpVersion",
		"health_check_interval":      "HealthCheckInterval",
		"health_check_method":        "HealthCheckMethod",
		"health_check_port":          "HealthCheckPort",
		"health_check_protocol":      "HealthCheckProtocol",
		"health_check_template_id":   "HealthCheckTemplateId",
		"health_check_template_name": "HealthCheckTemplateName",
		"health_check_timeout":       "HealthCheckTimeout",
		"health_check_uri":           "HealthCheckURI",
		"healthy_threshold":          "HealthyThreshold",
		"key":                        "Key",
		"project_name":               "ProjectName",
		"tags":                       "Tags",
		"unhealthy_threshold":        "UnhealthyThreshold",
		"update_time":                "UpdateTime",
		"value":                      "Value",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
