// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package rdsmssql

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_rdsmssql_allow_list", allowListDataSource)
}

// allowListDataSource returns the Terraform volcenginecc_rdsmssql_allow_list data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::RDSMsSQL::AllowList resource.
func allowListDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AllowList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP allowlist. Separate multiple IP addresses with commas (,). No duplicates allowed",
		//	  "type": "string"
		//	}
		"allow_list": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IP allowlist. Separate multiple IP addresses with commas (,). No duplicates allowed",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListCategory
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist category",
		//	  "type": "string"
		//	}
		"allow_list_category": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Allowlist category",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListDesc
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist description",
		//	  "type": "string"
		//	}
		"allow_list_desc": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Allowlist description",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListIPNum
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist IP count",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"allow_list_ip_num": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Allowlist IP count",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist ID",
		//	  "type": "string"
		//	}
		"allow_list_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Allowlist ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Allowlist name",
		//	  "type": "string"
		//	}
		"allow_list_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Allowlist name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AllowListType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP address type in the allowlist. Only IPv4 is supported",
		//	  "type": "string"
		//	}
		"allow_list_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IP address type in the allowlist. Only IPv4 is supported",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AssociatedInstanceNum
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of bound instances. Required when unbinding an instance from the allowlist",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"associated_instance_num": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of bound instances. Required when unbinding an instance from the allowlist",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: AssociatedInstances
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Bound instance list",
		//	  "insertionOrder": true,
		//	  "items": {
		//	    "properties": {
		//	      "InstanceId": {
		//	        "description": "Instance ID",
		//	        "type": "string"
		//	      },
		//	      "InstanceName": {
		//	        "description": "Instance name",
		//	        "type": "string"
		//	      },
		//	      "InstanceStatus": {
		//	        "description": "Instance status",
		//	        "type": "string"
		//	      },
		//	      "IsLatest": {
		//	        "description": "Sync latest allowlist IP",
		//	        "type": "boolean"
		//	      },
		//	      "ProjectName": {
		//	        "description": "Project name of the instance",
		//	        "type": "string"
		//	      },
		//	      "VPC": {
		//	        "description": "VPC ID of the instance",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"associated_instances": schema.ListNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: InstanceId
					"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance ID",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: InstanceName
					"instance_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance name",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: InstanceStatus
					"instance_status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Instance status",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: IsLatest
					"is_latest": schema.BoolAttribute{ /*START ATTRIBUTE*/
						Description: "Sync latest allowlist IP",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: ProjectName
					"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "Project name of the instance",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: VPC
					"vpc": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "VPC ID of the instance",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "Bound instance list",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: InstanceId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Instance ID",
		//	  "type": "string"
		//	}
		"instance_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Instance ID",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Project name",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Project name",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UserAllowList
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "IP addresses outside the security group that need to be added to the allowlist. Enter IP addresses or CIDR-formatted IP ranges. If both this field and AllowList are specified, AllowList takes precedence",
		//	  "type": "string"
		//	}
		"user_allow_list": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "IP addresses outside the security group that need to be added to the allowlist. Enter IP addresses or CIDR-formatted IP ranges. If both this field and AllowList are specified, AllowList takes precedence",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::RDSMsSQL::AllowList",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::RDSMsSQL::AllowList").WithTerraformTypeName("volcenginecc_rdsmssql_allow_list")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"allow_list":              "AllowList",
		"allow_list_category":     "AllowListCategory",
		"allow_list_desc":         "AllowListDesc",
		"allow_list_id":           "AllowListId",
		"allow_list_ip_num":       "AllowListIPNum",
		"allow_list_name":         "AllowListName",
		"allow_list_type":         "AllowListType",
		"associated_instance_num": "AssociatedInstanceNum",
		"associated_instances":    "AssociatedInstances",
		"instance_id":             "InstanceId",
		"instance_name":           "InstanceName",
		"instance_status":         "InstanceStatus",
		"is_latest":               "IsLatest",
		"project_name":            "ProjectName",
		"user_allow_list":         "UserAllowList",
		"vpc":                     "VPC",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
