// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package cbr

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddResourceFactory("volcenginecc_cbr_backup_policy", backupPolicyResource)
}

// backupPolicyResource returns the Terraform volcenginecc_cbr_backup_policy resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::CBR::BackupPolicy resource.
func backupPolicyResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Account ID that created this policy",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Account ID that created this policy",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: BackupType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Backup type. Values are as follows: FULL: full backup; INCREMENTAL: incremental backup",
		//	  "enum": [
		//	    "FULL",
		//	    "INCREMENTAL"
		//	  ],
		//	  "type": "string"
		//	}
		"backup_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Backup type. Values are as follows: FULL: full backup; INCREMENTAL: incremental backup",
			Required:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.OneOf(
					"FULL",
					"INCREMENTAL",
				),
			}, /*END VALIDATORS*/
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Creation time",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Creation time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Crontab
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Backup cycle, using a crontab expression",
		//	  "type": "string"
		//	}
		"crontab": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Backup cycle, using a crontab expression",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: EnablePolicy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Whether the policy is enabled. Values are as follows: true: policy enabled; false: policy disabled",
		//	  "type": "boolean"
		//	}
		"enable_policy": schema.BoolAttribute{ /*START ATTRIBUTE*/
			Description: "Whether the policy is enabled. Values are as follows: true: policy enabled; false: policy disabled",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Policy Name",
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Policy Name",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: PlanNumber
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Number of backup plans associated with this policy",
		//	  "type": "integer"
		//	}
		"plan_number": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Number of backup plans associated with this policy",
			Computed:    true,
			PlanModifiers: []planmodifier.Int64{ /*START PLAN MODIFIERS*/
				int64planmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: PolicyId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Backup Policy ID",
		//	  "type": "string"
		//	}
		"policy_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Backup Policy ID",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RetentionDay
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Restore point retention period. -1 means retain indefinitely. Other valid values range from [1, 999999]",
		//	  "type": "integer"
		//	}
		"retention_day": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Restore point retention period. -1 means retain indefinitely. Other valid values range from [1, 999999]",
			Required:    true,
		}, /*END ATTRIBUTE*/
		// Property: RetentionNumMax
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Maximum number of restore points retained",
		//	  "type": "integer"
		//	}
		"retention_num_max": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Maximum number of restore points retained",
			Required:    true,
			// RetentionNumMax is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: RetentionNumMin
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Minimum restore point retention limit",
		//	  "type": "integer"
		//	}
		"retention_num_min": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Minimum restore point retention limit",
			Required:    true,
			// RetentionNumMin is a write-only property.
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Update time",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Update time",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "The backup policy defines information such as backup cycle and backup type. Subsequently, backup plans associate the backup policy with backup storage space to achieve automatic backup",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::CBR::BackupPolicy").WithTerraformTypeName("volcenginecc_cbr_backup_policy")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":        "AccountId",
		"backup_type":       "BackupType",
		"created_time":      "CreatedTime",
		"crontab":           "Crontab",
		"enable_policy":     "EnablePolicy",
		"name":              "Name",
		"plan_number":       "PlanNumber",
		"policy_id":         "PolicyId",
		"retention_day":     "RetentionDay",
		"retention_num_max": "RetentionNumMax",
		"retention_num_min": "RetentionNumMin",
		"updated_time":      "UpdatedTime",
	})

	opts = opts.WithWriteOnlyPropertyPaths([]string{
		"/properties/RetentionNumMax",
		"/properties/RetentionNumMin",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/PolicyId",
		"/properties/AccountId",
		"/properties/CreatedTime",
		"/properties/PlanNumber",
		"/properties/UpdatedTime",
	})

	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
