// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/schema/main.go; DO NOT EDIT.
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_ecs_images -cctype Volcengine::ECS::Image -package ecs ../volcengine/ecs/image_plural_data_source_gen.go ../volcengine/ecs/image_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_tos_buckets -cctype Volcengine::TOS::Bucket -package tos ../volcengine/tos/bucket_plural_data_source_gen.go ../volcengine/tos/bucket_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_iam_groups -cctype Volcengine::IAM::Group -package iam ../volcengine/iam/group_plural_data_source_gen.go ../volcengine/iam/group_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_iam_users -cctype Volcengine::IAM::User -package iam ../volcengine/iam/user_plural_data_source_gen.go ../volcengine/iam/user_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_securitygroups -cctype Volcengine::VPC::SecurityGroup -package vpc ../volcengine/vpc/securitygroup_plural_data_source_gen.go ../volcengine/vpc/securitygroup_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_subnets -cctype Volcengine::VPC::Subnet -package vpc ../volcengine/vpc/subnet_plural_data_source_gen.go ../volcengine/vpc/subnet_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_iam_accesskeys -cctype Volcengine::IAM::Accesskey -package iam ../volcengine/iam/accesskey_plural_data_source_gen.go ../volcengine/iam/accesskey_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_enis -cctype Volcengine::VPC::ENI -package vpc ../volcengine/vpc/eni_plural_data_source_gen.go ../volcengine/vpc/eni_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_iam_policies -cctype Volcengine::IAM::Policy -package iam ../volcengine/iam/policy_plural_data_source_gen.go ../volcengine/iam/policy_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_eips -cctype Volcengine::VPC::EIP -package vpc ../volcengine/vpc/eip_plural_data_source_gen.go ../volcengine/vpc/eip_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_route_tables -cctype Volcengine::VPC::RouteTable -package vpc ../volcengine/vpc/route_table_plural_data_source_gen.go ../volcengine/vpc/route_table_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_ark_endpoints -cctype Volcengine::ARK::Endpoint -package ark ../volcengine/ark/endpoint_plural_data_source_gen.go ../volcengine/ark/endpoint_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_vpc_vpcs -cctype Volcengine::VPC::VPC -package vpc ../volcengine/vpc/vpc_plural_data_source_gen.go ../volcengine/vpc/vpc_plural_data_source_gen_test.go
//go:generate go run generators/plural-data-source/main.go -data-source volcenginecc_iam_roles -cctype Volcengine::IAM::Role -package iam ../volcengine/iam/role_plural_data_source_gen.go ../volcengine/iam/role_plural_data_source_gen_test.go

package provider

import (
	_ "github.com/volcengine/terraform-provider-volcenginecc/internal/volcengine/ark"
	_ "github.com/volcengine/terraform-provider-volcenginecc/internal/volcengine/ecs"
	_ "github.com/volcengine/terraform-provider-volcenginecc/internal/volcengine/iam"
	_ "github.com/volcengine/terraform-provider-volcenginecc/internal/volcengine/tos"
	_ "github.com/volcengine/terraform-provider-volcenginecc/internal/volcengine/vpc"
)
