// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/resource/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
	fwvalidators "github.com/volcengine/terraform-provider-volcenginecc/internal/validators"
)

func init() {
	registry.AddResourceFactory("volcenginecc_vpc_route_table", routeTableResource)
}

// routeTableResource returns the Terraform volcenginecc_vpc_route_table resource.
// This Terraform resource corresponds to the Cloud Control Volcengine::VPC::RouteTable resource.
func routeTableResource(ctx context.Context) (resource.Resource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: AccountId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表所属账号的ID。",
		//	  "type": "string"
		//	}
		"account_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表所属账号的ID。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: AssociateType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "创建路由表输入的关联类型。1、Subnet：子网关联。2、Gateway：网关关联。",
		//	  "enum": [
		//	    "Subnet",
		//	    "Gateway"
		//	  ],
		//	  "type": "string"
		//	}
		"associate_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "创建路由表输入的关联类型。1、Subnet：子网关联。2、Gateway：网关关联。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.OneOf(
					"Subnet",
					"Gateway",
				),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表创建时间。",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表创建时间。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: CustomRouteEntries
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表关联的自定义路由条目列表。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Description": {
		//	        "description": "路由条目描述。",
		//	        "maxLength": 255,
		//	        "type": "string"
		//	      },
		//	      "DestinationCidrBlock": {
		//	        "description": "路由条目的目标网段。",
		//	        "type": "string"
		//	      },
		//	      "DestinationPrefixListId": {
		//	        "description": "前缀列表ID。",
		//	        "type": "string"
		//	      },
		//	      "NextHopId": {
		//	        "description": "下一跳资源ID。",
		//	        "type": "string"
		//	      },
		//	      "NextHopName": {
		//	        "description": "路由条目下一跳资源的名称。",
		//	        "type": "string"
		//	      },
		//	      "NextHopType": {
		//	        "description": "自定义路由条目的下一跳的类型。1、Instance：ECS实例。2、HaVip：高可用虚拟IP。3、NetworkInterface：辅助网卡。4、NatGW：NAT网关。5、VpnGW：VPN网关。6、TransitRouter：中转路由器。7、IPv6GW：IPv6网关。8、CloudConnector：云连接器。9、GWLBEndpoint：网关负载均衡终端节点。",
		//	        "type": "string"
		//	      },
		//	      "PrefixListCidrBlocks": {
		//	        "description": "前缀列表的CIDR。",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "RouteEntryId": {
		//	        "description": "路由条目ID。",
		//	        "type": "string"
		//	      },
		//	      "RouteEntryName": {
		//	        "description": "路由条目名称。",
		//	        "type": "string"
		//	      },
		//	      "RouteTableId": {
		//	        "description": "路由表ID。",
		//	        "type": "string"
		//	      },
		//	      "Status": {
		//	        "description": "路由条目状态。1、Pending：待创建。2、Available：可用。",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "路由条目类型。1、Custom：自定义路由条目。2、System：系统默认路由条目。",
		//	        "enum": [
		//	          "Custom",
		//	          "System"
		//	        ],
		//	        "type": "string"
		//	      },
		//	      "VpcId": {
		//	        "description": "路由条目所属私有网络的ID。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"custom_route_entries": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目描述。",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							stringvalidator.LengthAtMost(255),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: DestinationCidrBlock
					"destination_cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目的目标网段。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: DestinationPrefixListId
					"destination_prefix_list_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "前缀列表ID。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: NextHopId
					"next_hop_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "下一跳资源ID。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: NextHopName
					"next_hop_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目下一跳资源的名称。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: NextHopType
					"next_hop_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "自定义路由条目的下一跳的类型。1、Instance：ECS实例。2、HaVip：高可用虚拟IP。3、NetworkInterface：辅助网卡。4、NatGW：NAT网关。5、VpnGW：VPN网关。6、TransitRouter：中转路由器。7、IPv6GW：IPv6网关。8、CloudConnector：云连接器。9、GWLBEndpoint：网关负载均衡终端节点。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: PrefixListCidrBlocks
					// Property: RouteEntryId
					// Property: RouteEntryName
					"route_entry_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目名称。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: RouteTableId
					// Property: Status
					// Property: Type
					// Property: VpcId
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "路由表关联的自定义路由条目列表。\n 特别提示: 在使用 ListNestedAttribute 或 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表描述信息。",
		//	  "maxLength": 255,
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表描述信息。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthAtMost(255),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Ipv4GatewayId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "关联路由表的IPv4网关ID。",
		//	  "type": "string"
		//	}
		"ipv_4_gateway_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "关联路由表的IPv4网关ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Ipv6GatewayId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "关联路由表的IPv6网关ID。",
		//	  "type": "string"
		//	}
		"ipv_6_gateway_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "关联路由表的IPv6网关ID。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: ProjectName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "default": "default",
		//	  "description": "路由表所属项目的名称。",
		//	  "type": "string"
		//	}
		"project_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表所属项目的名称。",
			Optional:    true,
			Computed:    true,
			Default:     stringdefault.StaticString("default"),
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
				stringplanmodifier.RequiresReplaceIfConfigured(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RouteTableId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表ID。",
		//	  "type": "string"
		//	}
		"route_table_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表ID。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RouteTableName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表名称。",
		//	  "maxLength": 128,
		//	  "minLength": 1,
		//	  "type": "string"
		//	}
		"route_table_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表名称。",
			Optional:    true,
			Computed:    true,
			Validators: []validator.String{ /*START VALIDATORS*/
				stringvalidator.LengthBetween(1, 128),
			}, /*END VALIDATORS*/
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: RouteTableType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表类型。1、Custom：自定义路由表。2、System：系统路由表。",
		//	  "enum": [
		//	    "Custom",
		//	    "System"
		//	  ],
		//	  "type": "string"
		//	}
		"route_table_type": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表类型。1、Custom：自定义路由表。2、System：系统路由表。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SubnetIds
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "关联的子网的ID列表。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "type": "string"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"subnet_ids": schema.SetAttribute{ /*START ATTRIBUTE*/
			ElementType: types.StringType,
			Description: "关联的子网的ID列表。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: SystemRouteEntries
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表关联的系统默认路由条目列表。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Description": {
		//	        "description": "路由条目描述。",
		//	        "maxLength": 255,
		//	        "type": "string"
		//	      },
		//	      "DestinationCidrBlock": {
		//	        "description": "路由条目的目标网段。",
		//	        "type": "string"
		//	      },
		//	      "DestinationPrefixListId": {
		//	        "description": "前缀列表ID。",
		//	        "type": "string"
		//	      },
		//	      "NextHopId": {
		//	        "description": "下一跳资源ID。",
		//	        "type": "string"
		//	      },
		//	      "NextHopName": {
		//	        "description": "路由条目下一跳资源的名称。",
		//	        "type": "string"
		//	      },
		//	      "NextHopType": {
		//	        "description": "自定义路由条目的下一跳的类型。1、Instance：ECS实例。2、HaVip：高可用虚拟IP。3、NetworkInterface：辅助网卡。4、NatGW：NAT网关。5、VpnGW：VPN网关。6、TransitRouter：中转路由器。7、IPv6GW：IPv6网关。8、CloudConnector：云连接器。9、GWLBEndpoint：网关负载均衡终端节点。",
		//	        "type": "string"
		//	      },
		//	      "PrefixListCidrBlocks": {
		//	        "description": "前缀列表的CIDR。",
		//	        "insertionOrder": false,
		//	        "items": {
		//	          "type": "string"
		//	        },
		//	        "type": "array",
		//	        "uniqueItems": true
		//	      },
		//	      "RouteEntryId": {
		//	        "description": "路由条目ID。",
		//	        "type": "string"
		//	      },
		//	      "RouteEntryName": {
		//	        "description": "路由条目名称。",
		//	        "type": "string"
		//	      },
		//	      "RouteTableId": {
		//	        "description": "路由表ID。",
		//	        "type": "string"
		//	      },
		//	      "Status": {
		//	        "description": "路由条目状态。1、Pending：待创建。2、Available：可用。",
		//	        "type": "string"
		//	      },
		//	      "Type": {
		//	        "description": "路由条目类型。1、Custom：自定义路由条目。2、System：系统默认路由条目。",
		//	        "enum": [
		//	          "Custom",
		//	          "System"
		//	        ],
		//	        "type": "string"
		//	      },
		//	      "VpcId": {
		//	        "description": "路由条目所属私有网络的ID。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"system_route_entries": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Description
					"description": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目描述。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: DestinationCidrBlock
					"destination_cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目的目标网段。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: DestinationPrefixListId
					"destination_prefix_list_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "前缀列表ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NextHopId
					"next_hop_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "下一跳资源ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NextHopName
					"next_hop_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目下一跳资源的名称。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: NextHopType
					"next_hop_type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "自定义路由条目的下一跳的类型。1、Instance：ECS实例。2、HaVip：高可用虚拟IP。3、NetworkInterface：辅助网卡。4、NatGW：NAT网关。5、VpnGW：VPN网关。6、TransitRouter：中转路由器。7、IPv6GW：IPv6网关。8、CloudConnector：云连接器。9、GWLBEndpoint：网关负载均衡终端节点。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: PrefixListCidrBlocks
					"prefix_list_cidr_blocks": schema.SetAttribute{ /*START ATTRIBUTE*/
						ElementType: types.StringType,
						Description: "前缀列表的CIDR。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: RouteEntryId
					"route_entry_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: RouteEntryName
					"route_entry_name": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目名称。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: RouteTableId
					"route_table_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由表ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Status
					"status": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目状态。1、Pending：待创建。2、Available：可用。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: Type
					"type": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目类型。1、Custom：自定义路由条目。2、System：系统默认路由条目。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
					// Property: VpcId
					"vpc_id": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "路由条目所属私有网络的ID。",
						Computed:    true,
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "路由表关联的系统默认路由条目列表。\n 特别提示: 在使用 ListNestedAttribute 或 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: Tags
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "标签列表。",
		//	  "insertionOrder": false,
		//	  "items": {
		//	    "properties": {
		//	      "Key": {
		//	        "description": "用户标签的标签键。",
		//	        "type": "string"
		//	      },
		//	      "Value": {
		//	        "description": "用户标签的标签值。",
		//	        "type": "string"
		//	      }
		//	    },
		//	    "required": [
		//	      "Key"
		//	    ],
		//	    "type": "object"
		//	  },
		//	  "type": "array",
		//	  "uniqueItems": true
		//	}
		"tags": schema.SetNestedAttribute{ /*START ATTRIBUTE*/
			NestedObject: schema.NestedAttributeObject{ /*START NESTED OBJECT*/
				Attributes: map[string]schema.Attribute{ /*START SCHEMA*/
					// Property: Key
					"key": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "用户标签的标签键。",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{ /*START VALIDATORS*/
							fwvalidators.NotNullString(),
						}, /*END VALIDATORS*/
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
					// Property: Value
					"value": schema.StringAttribute{ /*START ATTRIBUTE*/
						Description: "用户标签的标签值。",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
							stringplanmodifier.UseStateForUnknown(),
						}, /*END PLAN MODIFIERS*/
					}, /*END ATTRIBUTE*/
				}, /*END SCHEMA*/
			}, /*END NESTED OBJECT*/
			Description: "标签列表。\n 特别提示: 在使用 ListNestedAttribute 或 SetNestedAttribute 时，必须完整定义其嵌套结构体的所有属性。若定义不完整，Terraform 在执行计划对比时可能会检测到意料之外的差异，从而触发不必要的资源更新，影响资源的稳定性与可预测性。",
			Optional:    true,
			Computed:    true,
			PlanModifiers: []planmodifier.Set{ /*START PLAN MODIFIERS*/
				setplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表更新时间。",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表更新时间。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "路由表所属VPC的ID。",
		//	  "type": "string"
		//	}
		"vpc_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "路由表所属VPC的ID。",
			Required:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.RequiresReplace(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
		// Property: VpcName
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "VPC的名称。",
		//	  "type": "string"
		//	}
		"vpc_name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "VPC的名称。",
			Computed:    true,
			PlanModifiers: []planmodifier.String{ /*START PLAN MODIFIERS*/
				stringplanmodifier.UseStateForUnknown(),
			}, /*END PLAN MODIFIERS*/
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	// Corresponds to Cloud Control primaryIdentifier.
	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Computed:    true,
		PlanModifiers: []planmodifier.String{
			stringplanmodifier.UseStateForUnknown(),
		},
	}

	schema := schema.Schema{
		Description: "路由表由一系列路由条目组成，为私有网络的流量指定下一跳的云资源，每个子网必须且仅支持关联一个路由表，使子网内的资源通过路由表转发流量。",
		Version:     1,
		Attributes:  attributes,
	}

	var opts generic.ResourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::RouteTable").WithTerraformTypeName("volcenginecc_vpc_route_table")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"account_id":                 "AccountId",
		"associate_type":             "AssociateType",
		"created_time":               "CreatedTime",
		"custom_route_entries":       "CustomRouteEntries",
		"description":                "Description",
		"destination_cidr_block":     "DestinationCidrBlock",
		"destination_prefix_list_id": "DestinationPrefixListId",
		"ipv_4_gateway_id":           "Ipv4GatewayId",
		"ipv_6_gateway_id":           "Ipv6GatewayId",
		"key":                        "Key",
		"next_hop_id":                "NextHopId",
		"next_hop_name":              "NextHopName",
		"next_hop_type":              "NextHopType",
		"prefix_list_cidr_blocks":    "PrefixListCidrBlocks",
		"project_name":               "ProjectName",
		"route_entry_id":             "RouteEntryId",
		"route_entry_name":           "RouteEntryName",
		"route_table_id":             "RouteTableId",
		"route_table_name":           "RouteTableName",
		"route_table_type":           "RouteTableType",
		"status":                     "Status",
		"subnet_ids":                 "SubnetIds",
		"system_route_entries":       "SystemRouteEntries",
		"tags":                       "Tags",
		"type":                       "Type",
		"updated_time":               "UpdatedTime",
		"value":                      "Value",
		"vpc_id":                     "VpcId",
		"vpc_name":                   "VpcName",
	})

	opts = opts.WithReadOnlyPropertyPaths([]string{
		"/properties/AccountId",
		"/properties/RouteTableId",
		"/properties/RouteTableType",
		"/properties/UpdatedTime",
		"/properties/CreatedTime",
		"/properties/VpcName",
		"/properties/SystemRouteEntries",
		"/properties/CustomRouteEntries/*/RouteEntryId",
		"/properties/CustomRouteEntries/*/PrefixListCidrBlocks",
		"/properties/CustomRouteEntries/*/RouteTableId",
		"/properties/CustomRouteEntries/*/Status",
		"/properties/CustomRouteEntries/*/Type",
		"/properties/CustomRouteEntries/*/VpcId",
	})

	opts = opts.WithCreateOnlyPropertyPaths([]string{
		"/properties/ProjectName",
		"/properties/AssociateType",
		"/properties/VpcId",
	})
	opts = opts.WithCreateTimeoutInMinutes(0).WithDeleteTimeoutInMinutes(0)

	opts = opts.WithUpdateTimeoutInMinutes(0)

	v, err := generic.NewResource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
