// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package vpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_vpc_traffic_mirror_filter_rule", trafficMirrorFilterRuleDataSource)
}

// trafficMirrorFilterRuleDataSource returns the Terraform volcenginecc_vpc_traffic_mirror_filter_rule data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::VPC::TrafficMirrorFilterRule resource.
func trafficMirrorFilterRuleDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Description of the filtering rule.",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Description of the filtering rule.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationCidrBlock
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination network segment.",
		//	  "type": "string"
		//	}
		"destination_cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination network segment.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DestinationPortRange
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Destination port range for traffic. When Protocol is all or icmp, this parameter is not required. The default value is -1/-1, which means no port restriction. When Protocol is tcp or udp, this parameter is required. Valid range is 1–65535. Use a forward slash (/) to separate the start and end ports, such as 1/50, 80/80.",
		//	  "type": "string"
		//	}
		"destination_port_range": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Destination port range for traffic. When Protocol is all or icmp, this parameter is not required. The default value is -1/-1, which means no port restriction. When Protocol is tcp or udp, this parameter is required. Valid range is 1–65535. Use a forward slash (/) to separate the start and end ports, such as 1/50, 80/80.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Policy
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Traffic capture policy. accept: allow. When traffic from the mirror source matches this rule, the traffic is copied to the mirror target for monitoring and analysis. reject: reject. When traffic from the mirror source matches this rule, the traffic is not copied and monitoring and analysis are not performed.",
		//	  "enum": [
		//	    "accept",
		//	    "reject"
		//	  ],
		//	  "type": "string"
		//	}
		"policy": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Traffic capture policy. accept: allow. When traffic from the mirror source matches this rule, the traffic is copied to the mirror target for monitoring and analysis. reject: reject. When traffic from the mirror source matches this rule, the traffic is not copied and monitoring and analysis are not performed.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Priority
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Priority of the filtering rule, ranging from 1 to 1000. The smaller the value, the higher the priority. Default is 1, which is the highest priority. For the same filtering condition and direction, the priority must be unique.",
		//	  "format": "int64",
		//	  "type": "integer"
		//	}
		"priority": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "Priority of the filtering rule, ranging from 1 to 1000. The smaller the value, the higher the priority. Default is 1, which is the highest priority. For the same filtering condition and direction, the priority must be unique.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Protocol
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Traffic protocol. Valid values: all: includes TCP, UDP, and ICMP protocols. tcp: TCP protocol. udp: UDP protocol. icmp: ICMP protocol.",
		//	  "enum": [
		//	    "all",
		//	    "tcp",
		//	    "udp",
		//	    "icmp"
		//	  ],
		//	  "type": "string"
		//	}
		"protocol": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Traffic protocol. Valid values: all: includes TCP, UDP, and ICMP protocols. tcp: TCP protocol. udp: UDP protocol. icmp: ICMP protocol.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourceCidrBlock
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source network segment.",
		//	  "type": "string"
		//	}
		"source_cidr_block": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source network segment.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: SourcePortRange
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Source port range for traffic. When Protocol is all or icmp, this parameter is not required. The default value is -1/-1, which means no port restriction. When Protocol is tcp or udp, this parameter is required. Valid range is 1–65535. Use a forward slash (/) to separate the start and end ports, such as 1/50, 80/80.",
		//	  "type": "string"
		//	}
		"source_port_range": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Source port range for traffic. When Protocol is all or icmp, this parameter is not required. The default value is -1/-1, which means no port restriction. When Protocol is tcp or udp, this parameter is required. Valid range is 1–65535. Use a forward slash (/) to separate the start and end ports, such as 1/50, 80/80.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Status
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Status of the filtering rule. Available: available. Deleting: deleting. Creating: creating. Pending: modifying.",
		//	  "type": "string"
		//	}
		"status": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Status of the filtering rule. Available: available. Deleting: deleting. Creating: creating. Pending: modifying.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TrafficDirection
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Traffic direction. Valid values: ingress: inbound rule. egress: outbound rule.",
		//	  "enum": [
		//	    "ingress",
		//	    "egress"
		//	  ],
		//	  "type": "string"
		//	}
		"traffic_direction": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Traffic direction. Valid values: ingress: inbound rule. egress: outbound rule.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TrafficMirrorFilterId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Filtering condition ID.",
		//	  "type": "string"
		//	}
		"traffic_mirror_filter_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Filtering condition ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: TrafficMirrorFilterRuleId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "Filtering rule ID.",
		//	  "type": "string"
		//	}
		"traffic_mirror_filter_rule_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "Filtering rule ID.",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::VPC::TrafficMirrorFilterRule",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::VPC::TrafficMirrorFilterRule").WithTerraformTypeName("volcenginecc_vpc_traffic_mirror_filter_rule")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"description":                   "Description",
		"destination_cidr_block":        "DestinationCidrBlock",
		"destination_port_range":        "DestinationPortRange",
		"policy":                        "Policy",
		"priority":                      "Priority",
		"protocol":                      "Protocol",
		"source_cidr_block":             "SourceCidrBlock",
		"source_port_range":             "SourcePortRange",
		"status":                        "Status",
		"traffic_direction":             "TrafficDirection",
		"traffic_mirror_filter_id":      "TrafficMirrorFilterId",
		"traffic_mirror_filter_rule_id": "TrafficMirrorFilterRuleId",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
