// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by generators/singular-data-source/main.go; DO NOT EDIT.

package organization

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/generic"
	"github.com/volcengine/terraform-provider-volcenginecc/internal/registry"
)

func init() {
	registry.AddDataSourceFactory("volcenginecc_organization_unit", unitDataSource)
}

// unitDataSource returns the Terraform volcenginecc_organization_unit data source.
// This Terraform data source corresponds to the Cloud Control Volcengine::Organization::Unit resource.
func unitDataSource(ctx context.Context) (datasource.DataSource, error) {
	attributes := map[string]schema.Attribute{ /*START SCHEMA*/
		// Property: CreatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "创建时间。",
		//	  "type": "string"
		//	}
		"created_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "创建时间。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DeleteUk
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "删除标识。",
		//	  "type": "string"
		//	}
		"delete_uk": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "删除标识。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: DeletedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "删除时间。",
		//	  "type": "string"
		//	}
		"deleted_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "删除时间。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Depth
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "深度。",
		//	  "type": "integer"
		//	}
		"depth": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "深度。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Description
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "描述。",
		//	  "type": "string"
		//	}
		"description": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "描述。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Name
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "组织单元名称。",
		//	  "type": "string"
		//	}
		"name": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "组织单元名称。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OrgID
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "组织ID。",
		//	  "type": "string"
		//	}
		"org_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "组织ID。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OrgType
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "组织类型。企业组织： 1",
		//	  "type": "integer"
		//	}
		"org_type": schema.Int64Attribute{ /*START ATTRIBUTE*/
			Description: "组织类型。企业组织： 1",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: OrgUnitId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "组织单元ID。",
		//	  "type": "string"
		//	}
		"org_unit_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "组织单元ID。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: Owner
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "管理员ID。",
		//	  "type": "string"
		//	}
		"owner": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "管理员ID。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: ParentId
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "父单元Id。",
		//	  "type": "string"
		//	}
		"parent_id": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "父单元Id。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
		// Property: UpdatedTime
		// Cloud Control resource type schema:
		//
		//	{
		//	  "description": "更新时间。",
		//	  "type": "string"
		//	}
		"updated_time": schema.StringAttribute{ /*START ATTRIBUTE*/
			Description: "更新时间。",
			Computed:    true,
		}, /*END ATTRIBUTE*/
	} /*END SCHEMA*/

	attributes["id"] = schema.StringAttribute{
		Description: "Uniquely identifies the resource.",
		Required:    true,
	}

	schema := schema.Schema{
		Description: "Data Source schema for Volcengine::Organization::Unit",
		Attributes:  attributes,
	}

	var opts generic.DataSourceOptions

	opts = opts.WithCloudControlTypeName("Volcengine::Organization::Unit").WithTerraformTypeName("volcenginecc_organization_unit")
	opts = opts.WithTerraformSchema(schema)
	opts = opts.WithAttributeNameMap(map[string]string{
		"created_time": "CreatedTime",
		"delete_uk":    "DeleteUk",
		"deleted_time": "DeletedTime",
		"depth":        "Depth",
		"description":  "Description",
		"name":         "Name",
		"org_id":       "OrgID",
		"org_type":     "OrgType",
		"org_unit_id":  "OrgUnitId",
		"owner":        "Owner",
		"parent_id":    "ParentId",
		"updated_time": "UpdatedTime",
	})

	v, err := generic.NewSingularDataSource(ctx, opts...)

	if err != nil {
		return nil, err
	}

	return v, nil
}
